<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Administration_login extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Administration_login_model');
        $this->load->helper(array("datatable"));
    }

    /*
     * Listing of administration_logins
     */

    function index() {
        $data['_view'] = 'administration_login/index';
        $this->load->view('layouts/main', $data);
    }

    /**
     * Function to get all admin fund allocations
     * 
     * @return json result
     */
    function getAllAdminLogins() {
        $request = $_GET;
        $result = $this->Administration_login_model->get_all_administration_logins($request, array());
        echo json_encode($result);
        exit;
    }

    /*
     * Adding a new administration_login
     */

    function add() {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'EMP_ID' => $this->input->post('EMP_ID'),
                'LOGIN_USERNAME' => $this->input->post('LOGIN_USERNAME'),
                'LOGIN_PASSWORD' => $this->input->post('LOGIN_PASSWORD'),
            );

            $administration_login_id = $this->Administration_login_model->add_administration_login($params);
            redirect('administration_login/index');
        } else {
            $data['_view'] = 'administration_login/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a administration_login
     */

    function edit($LOGIN_ID) {
        // check if the administration_login exists before trying to edit it
        $data['administration_login'] = $this->Administration_login_model->get_administration_login($LOGIN_ID);

        if (isset($data['administration_login']['LOGIN_ID'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'EMP_ID' => $this->input->post('EMP_ID'),
                    'LOGIN_USERNAME' => $this->input->post('LOGIN_USERNAME'),
                    'LOGIN_PASSWORD' => $this->input->post('LOGIN_PASSWORD'),
                );

                $this->Administration_login_model->update_administration_login($LOGIN_ID, $params);
                redirect('administration_login/index');
            } else {
                $data['_view'] = 'administration_login/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The administration_login you are trying to edit does not exist.');
    }

    /*
     * Deleting administration_login
     */

    function remove($LOGIN_ID) {
        $administration_login = $this->Administration_login_model->get_administration_login($LOGIN_ID);

        // check if the administration_login exists before trying to delete it
        if (isset($administration_login['LOGIN_ID'])) {
            $this->Administration_login_model->delete_administration_login($LOGIN_ID);
            redirect('administration_login/index');
        } else
            show_error('The administration_login you are trying to delete does not exist.');
    }

}
