<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Administration_fundallocation extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model(array('Administration_fundallocation_model', 'Administration_employee_model'));
        $this->load->helper(array("datatable"));
        $this->load->library(array("form_validation", "PostData"));
        $session_data = (isset($this->session->userdata['EMP_DATA']) && !empty($this->session->userdata['EMP_DATA'])) ? $this->session->userdata['EMP_DATA'] : array();
        if (empty($session_data))
            redirect("login");
    }

    /*
     * Listing of administration_fundallocation
     */

    function index() {
        $data['_view'] = 'administration_fundallocation/index';
        $this->load->view('layouts/main', $data);
    }

    /**
     * Function to get all admin fund allocations
     * 
     * @return json result
     */
    function getAllAdminFundallocations() {
        $request = $_GET;
        $result = $this->Administration_fundallocation_model->get_all_administration_fundallocation($request, array());
        echo json_encode($result);
        exit;
    }

    /*
     * Adding a new administration_fundallocation
     */

    function add() {
        $postData = $this->input->post(NULL, TRUE);
        $conditions = array("IS_ACTIVE" => 1, "EMP_ID !=" => 1, "CREATED_BY" => $this->session->userdata['EMP_DATA']['EMP_ID']);
        $data['all_administration_employees'] = $this->Administration_employee_model->get_all_administration_employees_data($conditions);
        if (!empty($postData)) {
            if ($this->form_validation->run("admin_fund_form") == TRUE) {
                $admin_fund_data = $this->postdata->getAdminFundPostData($postData);
                $administration_fundallocation_id = $this->Administration_fundallocation_model->add_administration_fundallocation($admin_fund_data);
                redirect('administration_fundallocation/index');
            } else {
                $data['_view'] = 'administration_fundallocation/add';
                $this->load->view('layouts/main', $data);
            }
        } else {
            $data['_view'] = 'administration_fundallocation/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a administration_fundallocation
     */

    function edit($FA_ID) {
        // check if the administration_fundallocation exists before trying to edit it
        $data['administration_fundallocation'] = $this->Administration_fundallocation_model->get_administration_fundallocation($FA_ID);
        $postData = $this->input->post(NULL, TRUE);
        $conditions = array("IS_ACTIVE" => 1, "EMP_ID !=" => 1, "CREATED_BY" => $this->session->userdata['EMP_DATA']['EMP_ID']);
        $data['all_administration_employees'] = $this->Administration_employee_model->get_all_administration_employees_data($conditions);
        if (isset($postData) && !empty($postData)) {
            if ($this->form_validation->run("admin_fund_form") == TRUE) {
                $admin_fund_data = $this->postdata->getAdminFundPostData($postData, TRUE);
                $this->Administration_fundallocation_model->update_administration_fundallocation($FA_ID, $admin_fund_data);
                redirect('administration_fundallocation/index');
            } else {
                $data['_view'] = 'administration_fundallocation/edit';
                $this->load->view('layouts/main', $data);
            }
        } else {
            $data['_view'] = 'administration_fundallocation/edit';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Deleting administration_fundallocation
     */

    function remove() {
        $request = $_POST;
        $administration_fundallocation = $this->Administration_fundallocation_model->get_administration_fundallocation($request['id']);
        if (isset($administration_fundallocation['FA_ID'])) {
            $status = $this->Administration_fundallocation_model->delete_administration_fundallocation($request['id']);
            if ($status) {
                echo json_encode(array("status" => "success", "message" => "You have successfully removed " . $administration_fundallocation['FA_ID'] . "."));
                exit;
            }
            echo json_encode(array("status" => "error", "message" => "Some thing went wrong."));
            exit;
        } else {
            echo json_encode(array("status" => "error", "message" => "The client_info you are trying to delete does not exist."));
            exit;
        }
    }

}
