<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Administration_fundallocation extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Administration_fundallocation_model');
    } 

    /*
     * Listing of administration_fundallocation
     */
    function index()
    {
        $data['administration_fundallocation'] = $this->Administration_fundallocation_model->get_all_administration_fundallocation();

        $data['_view'] = 'administration_fundallocation/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new administration_fundallocation
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('Amount','Amount','numeric');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'FA_DATE' => $this->input->post('FA_DATE'),
				'EMP_ID' => $this->input->post('EMP_ID'),
				'Amount' => $this->input->post('Amount'),
				'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
				'CREATED_BY' => $this->input->post('CREATED_BY'),
				'CREATED_DATE' => $this->input->post('CREATED_DATE'),
				'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
				'MODIFIED_BY' => $this->input->post('MODIFIED_BY'),
            );
            
            $administration_fundallocation_id = $this->Administration_fundallocation_model->add_administration_fundallocation($params);
            redirect('administration_fundallocation/index');
        }
        else
        {
			$this->load->model('Administration_employee_model');
			$data['all_administration_employees'] = $this->Administration_employee_model->get_all_administration_employees();
            
            $data['_view'] = 'administration_fundallocation/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a administration_fundallocation
     */
    function edit($FA_ID)
    {   
        // check if the administration_fundallocation exists before trying to edit it
        $data['administration_fundallocation'] = $this->Administration_fundallocation_model->get_administration_fundallocation($FA_ID);
        
        if(isset($data['administration_fundallocation']['FA_ID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('Amount','Amount','numeric');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'FA_DATE' => $this->input->post('FA_DATE'),
					'EMP_ID' => $this->input->post('EMP_ID'),
					'Amount' => $this->input->post('Amount'),
					'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
					'CREATED_BY' => $this->input->post('CREATED_BY'),
					'CREATED_DATE' => $this->input->post('CREATED_DATE'),
					'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
					'MODIFIED_BY' => $this->input->post('MODIFIED_BY'),
                );

                $this->Administration_fundallocation_model->update_administration_fundallocation($FA_ID,$params);            
                redirect('administration_fundallocation/index');
            }
            else
            {
				$this->load->model('Administration_employee_model');
				$data['all_administration_employees'] = $this->Administration_employee_model->get_all_administration_employees();

                $data['_view'] = 'administration_fundallocation/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The administration_fundallocation you are trying to edit does not exist.');
    } 

    /*
     * Deleting administration_fundallocation
     */
    function remove($FA_ID)
    {
        $administration_fundallocation = $this->Administration_fundallocation_model->get_administration_fundallocation($FA_ID);

        // check if the administration_fundallocation exists before trying to delete it
        if(isset($administration_fundallocation['FA_ID']))
        {
            $this->Administration_fundallocation_model->delete_administration_fundallocation($FA_ID);
            redirect('administration_fundallocation/index');
        }
        else
            show_error('The administration_fundallocation you are trying to delete does not exist.');
    }
    
}
