<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Client_info extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Client_info_model');
    } 

    /*
     * Listing of client_info
     */
    function index()
    {
        $data['client_info'] = $this->Client_info_model->get_all_client_info();

        $data['_view'] = 'client_info/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new client_info
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('CLIENT_CODE','CLIENT CODE','required');
		$this->form_validation->set_rules('CLIENT_NAME','CLIENT NAME','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'CLIENT_CODE' => $this->input->post('CLIENT_CODE'),
				'CLIENT_NAME' => $this->input->post('CLIENT_NAME'),
				'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
				'CREATED_DATE' => $this->input->post('CREATED_DATE'),
				'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
            );
            
            $client_info_id = $this->Client_info_model->add_client_info($params);
            redirect('client_info/index');
        }
        else
        {            
            $data['_view'] = 'client_info/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a client_info
     */
    function edit($CLIENT_ID)
    {   
        // check if the client_info exists before trying to edit it
        $data['client_info'] = $this->Client_info_model->get_client_info($CLIENT_ID);
        
        if(isset($data['client_info']['CLIENT_ID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('CLIENT_CODE','CLIENT CODE','required');
			$this->form_validation->set_rules('CLIENT_NAME','CLIENT NAME','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'CLIENT_CODE' => $this->input->post('CLIENT_CODE'),
					'CLIENT_NAME' => $this->input->post('CLIENT_NAME'),
					'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
					'CREATED_DATE' => $this->input->post('CREATED_DATE'),
					'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
                );

                $this->Client_info_model->update_client_info($CLIENT_ID,$params);            
                redirect('client_info/index');
            }
            else
            {
                $data['_view'] = 'client_info/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The client_info you are trying to edit does not exist.');
    } 

    /*
     * Deleting client_info
     */
    function remove($CLIENT_ID)
    {
        $client_info = $this->Client_info_model->get_client_info($CLIENT_ID);

        // check if the client_info exists before trying to delete it
        if(isset($client_info['CLIENT_ID']))
        {
            $this->Client_info_model->delete_client_info($CLIENT_ID);
            redirect('client_info/index');
        }
        else
            show_error('The client_info you are trying to delete does not exist.');
    }
    
}
