<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Customer_reference extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Customer_reference_model');
        $session_data = (isset($this->session->userdata['EMP_DATA']) && !empty($this->session->userdata['EMP_DATA'])) ? $this->session->userdata['EMP_DATA'] : array();
        if (empty($session_data))
            redirect("login");
    }

    /*
     * Listing of customer_reference
     */

    function index() {
        $data['customer_reference'] = $this->Customer_reference_model->get_all_customer_reference();

        $data['_view'] = 'customer_reference/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new customer_reference
     */

    function add() {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'CUSTOMER_ID' => $this->input->post('CUSTOMER_ID'),
                'REFERENCE_NAME' => $this->input->post('REFERENCE_NAME'),
                'REFERENCE_IDNO' => $this->input->post('REFERENCE_IDNO'),
                'REFERENCE_RELATION' => $this->input->post('REFERENCE_RELATION'),
                'ADDRESS_KEY' => $this->input->post('ADDRESS_KEY'),
                'ACTUAL_ADDRESS' => $this->input->post('ACTUAL_ADDRESS'),
                'CITY' => $this->input->post('CITY'),
                'STATE_ID' => $this->input->post('STATE_ID'),
                'POSTCODE' => $this->input->post('POSTCODE'),
                'PHONE1' => $this->input->post('PHONE1'),
                'PHONE2' => $this->input->post('PHONE2'),
                'FAX' => $this->input->post('FAX'),
                'CREATED_DATE' => $this->input->post('CREATED_DATE'),
                'CREATED_BY' => $this->input->post('CREATED_BY'),
                'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
                'MODIFIED_BY' => $this->input->post('MODIFIED_BY'),
                'CLIENT_ID' => $this->input->post('CLIENT_ID'),
                'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
            );

            $customer_reference_id = $this->Customer_reference_model->add_customer_reference($params);
            redirect('customer_reference/index');
        } else {
            $data['_view'] = 'customer_reference/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a customer_reference
     */

    function edit($REFERENCE_ID) {
        // check if the customer_reference exists before trying to edit it
        $data['customer_reference'] = $this->Customer_reference_model->get_customer_reference($REFERENCE_ID);

        if (isset($data['customer_reference']['REFERENCE_ID'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'CUSTOMER_ID' => $this->input->post('CUSTOMER_ID'),
                    'REFERENCE_NAME' => $this->input->post('REFERENCE_NAME'),
                    'REFERENCE_IDNO' => $this->input->post('REFERENCE_IDNO'),
                    'REFERENCE_RELATION' => $this->input->post('REFERENCE_RELATION'),
                    'ADDRESS_KEY' => $this->input->post('ADDRESS_KEY'),
                    'ACTUAL_ADDRESS' => $this->input->post('ACTUAL_ADDRESS'),
                    'CITY' => $this->input->post('CITY'),
                    'STATE_ID' => $this->input->post('STATE_ID'),
                    'POSTCODE' => $this->input->post('POSTCODE'),
                    'PHONE1' => $this->input->post('PHONE1'),
                    'PHONE2' => $this->input->post('PHONE2'),
                    'FAX' => $this->input->post('FAX'),
                    'CREATED_DATE' => $this->input->post('CREATED_DATE'),
                    'CREATED_BY' => $this->input->post('CREATED_BY'),
                    'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
                    'MODIFIED_BY' => $this->input->post('MODIFIED_BY'),
                    'CLIENT_ID' => $this->input->post('CLIENT_ID'),
                    'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
                );

                $this->Customer_reference_model->update_customer_reference($REFERENCE_ID, $params);
                redirect('customer_reference/index');
            } else {
                $data['_view'] = 'customer_reference/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The customer_reference you are trying to edit does not exist.');
    }

    /*
     * Deleting customer_reference
     */

    function remove($REFERENCE_ID) {
        $customer_reference = $this->Customer_reference_model->get_customer_reference($REFERENCE_ID);

        // check if the customer_reference exists before trying to delete it
        if (isset($customer_reference['REFERENCE_ID'])) {
            $this->Customer_reference_model->delete_customer_reference($REFERENCE_ID);
            redirect('customer_reference/index');
        } else
            show_error('The customer_reference you are trying to delete does not exist.');
    }

}
