<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Customer_detail extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Customer_detail_model');
        $this->load->model('file_model');
        $session_data = (isset($this->session->userdata['EMP_DATA']) && !empty($this->session->userdata['EMP_DATA'])) ? $this->session->userdata['EMP_DATA'] : array();
        if (empty($session_data))
            redirect("login");
    }

    /*
     * Listing of customer_details
     */

    function index() {
        $data['customer_details'] = $this->Customer_detail_model->get_all_customer_details();

        $data['_view'] = 'customer_detail/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new customer_detail
     */

    function add() {
        $this->load->library('form_validation');
        /*
          Docs checklist upload code starts

         */
        $data = array();
        //echo "<pre>";print_r($_FILES);exit;
        if (!empty($_FILES['userFiles']['name'])) {
            $filesCount = count($_FILES['userFiles']['name']);
            for ($i = 0; $i < $filesCount; $i++) {
                $_FILES['userFile']['name'] = $_FILES['userFiles']['name'][$i];
                $_FILES['userFile']['type'] = $_FILES['userFiles']['type'][$i];
                $_FILES['userFile']['tmp_name'] = $_FILES['userFiles']['tmp_name'][$i];
                $_FILES['userFile']['error'] = $_FILES['userFiles']['error'][$i];
                $_FILES['userFile']['size'] = $_FILES['userFiles']['size'][$i];

                $uploadPath = 'uploads/files/';
                $config['upload_path'] = $uploadPath;
                $config['allowed_types'] = 'gif|jpg|png';

                $this->load->library('upload', $config);
                $this->upload->initialize($config);
                if ($this->upload->do_upload('userFile')) {
                    $fileData = $this->upload->data();
                    $uploadData[$i]['DOCUMENT_PIC_PATH'] = $fileData['file_name'];
                    $uploadData[$i]['CREATED_DATE'] = date("Y-m-d H:i:s");
                    $uploadData[$i]['MODIFIED_DATE'] = date("Y-m-d H:i:s");
                }
            }

            if (!empty($uploadData)) {
                //Insert file information into the database
                $insert = $this->file_model->insert($uploadData);
                $statusMsg = $insert ? 'Files uploaded successfully.' : 'Some problem occurred, please try again.';
                $this->session->set_flashdata('statusMsg', $statusMsg);
            }
        }



        /*
          Docs checklist upload code ends

         */

        $this->form_validation->set_rules('CUSTOMER_TYPE', 'CUSTOMER TYPE', 'required');
        $this->form_validation->set_rules('CUSTOMER_IDNO', 'CUSTOMER IDNO', 'required');
        $this->form_validation->set_rules('CUSTOMER_NAME', 'CUSTOMER NAME', 'required');
        $this->form_validation->set_rules('EMAIL_ID', 'EMAIL ID', 'required|valid_email');
        $this->form_validation->set_rules('AGE', 'AGE', 'integer');
        $this->form_validation->set_rules('CREDIT_LIMIT', 'CREDIT LIMIT', 'numeric');
        $this->form_validation->set_rules('PRESENT_SALARY', 'PRESENT SALARY', 'numeric');
        $this->form_validation->set_rules('SPOUSE_EMAILID', 'SPOUSE EMAILID', 'valid_email');
        $this->form_validation->set_rules('SPOUSE_HOME_PHONE', 'SPOUSE HOME PHONE', 'integer');
        $this->form_validation->set_rules('SPOUSE_NO_OF_CHILDREN', 'SPOUSE NO OF CHILDREN', 'integer');
        $this->form_validation->set_rules('SPOUSE_AGE', 'SPOUSE AGE', 'integer');
        $this->form_validation->set_rules('GUARANTER_EMAILID', 'GUARANTER EMAILID', 'valid_email');
        $this->form_validation->set_rules('GUARANTER_HOME_PHONE', 'GUARANTER HOME PHONE', 'integer');
        $this->form_validation->set_rules('GUARANTER_HAND_PHONE', 'GUARANTER HAND PHONE', 'integer');
        $this->form_validation->set_rules('GUARANTER_AGE', 'GUARANTER AGE', 'numeric');
        $this->form_validation->set_rules('GUARANTER_NO_OF_CHILDREN', 'GUARANTER NO OF CHILDREN', 'integer');
        $this->form_validation->set_rules('GUARANTER_SALARY', 'GUARANTER SALARY', 'numeric');
        $this->form_validation->set_rules('GUARANTER_OFFICE_PHONE1', 'GUARANTER OFFICE PHONE1', 'integer');
        $this->form_validation->set_rules('GUARANTER_OFFICE_PHONE2', 'GUARANTER OFFICE PHONE2', 'integer');
        $this->form_validation->set_rules('APPLICABLE_AMOUNT', 'APPLICABLE AMOUNT', 'numeric');
        $this->form_validation->set_rules('APPLIED_AMOUNT', 'APPLIED AMOUNT', 'numeric');

        if ($this->form_validation->run()) {

            $params = array(
                'CUSTOMER_TYPE' => $this->input->post('CUSTOMER_TYPE'),
                'CUSTOMER_PIC_PATH' => $this->input->post('CUSTOMER_PIC_PATH'),
                'CUSTOMER_IDNO' => $this->input->post('CUSTOMER_IDNO'),
                'CUSTOMER_NAME' => $this->input->post('CUSTOMER_NAME'),
                'FILE_NO' => $this->input->post('FILE_NO'),
                'OLDIC_NO' => $this->input->post('OLDIC_NO'),
                'NON_ICNO' => $this->input->post('NON_ICNO'),
                'APPLICATION_DATE' => $this->input->post('APPLICATION_DATE'),
                'AGENT_ID' => $this->input->post('AGENT_ID'),
                'VEHICLE_NO' => $this->input->post('VEHICLE_NO'),
                'RELATED_TO_EMP' => $this->input->post('RELATED_TO_EMP'),
                'ADVERTISEMENT_ID' => $this->input->post('ADVERTISEMENT_ID'),
                'DOB' => $this->input->post('DOB'),
                'AGE' => $this->input->post('AGE'),
                'GENDER' => $this->input->post('GENDER'),
                'HOUSESTATUS_ID' => $this->input->post('HOUSESTATUS_ID'),
                'MARTIAL_STATUS' => $this->input->post('MARTIAL_STATUS'),
                'EMAIL_ID' => $this->input->post('EMAIL_ID'),
                'APPLIED_BRANCH_ID' => $this->input->post('APPLIED_BRANCH_ID'),
                'COMPANY_ID' => $this->input->post('COMPANY_ID'),
                'OCCUPATION_DEPT_NAME' => $this->input->post('OCCUPATION_DEPT_NAME'),
                'RACE_ID' => $this->input->post('RACE_ID'),
                'PRESENT_SALARY' => $this->input->post('PRESENT_SALARY'),
                'JOBSECTOR_ID' => $this->input->post('JOBSECTOR_ID'),
                'YEARS_OR_SERVICE_YEARS' => $this->input->post('YEARS_OR_SERVICE_YEARS'),
                'YEARS_OR_SERVICE_MONTHS' => $this->input->post('YEARS_OR_SERVICE_MONTHS'),
                'CREDIT_LIMIT' => $this->input->post('CREDIT_LIMIT'),
                'BANK_ID' => $this->input->post('BANK_ID'),
                'BANK_ACCOUNTNO' => $this->input->post('BANK_ACCOUNTNO'),
                'BANK_ATM_CARD_NO' => $this->input->post('BANK_ATM_CARD_NO'),
                'BANK_ATM_CARD_PIN_NO' => $this->input->post('BANK_ATM_CARD_PIN_NO'),
                'BANK_ATM_CARD_VALIDITY' => $this->input->post('BANK_ATM_CARD_VALIDITY'),
                'INTERNET_BANKING_USER_NAME' => $this->input->post('INTERNET_BANKING_USER_NAME'),
                'INTERNET_BANKING_PASSWORD' => $this->input->post('INTERNET_BANKING_PASSWORD'),
                'MONEY_DEPOSIT_BANK_ID' => $this->input->post('MONEY_DEPOSIT_BANK_ID'),
                'MONEY_DEPOSIT_ACCOUNT_NO' => $this->input->post('MONEY_DEPOSIT_ACCOUNT_NO'),
                'MONEY_DEPOSIT_ACCOUNT_HOLDER_NAME' => $this->input->post('MONEY_DEPOSIT_ACCOUNT_HOLDER_NAME'),
                'SPOUSE_PIC_PATH' => $this->input->post('SPOUSE_PIC_PATH'),
                'SPOUSE_IDNO' => $this->input->post('SPOUSE_IDNO'),
                'SPOUSE_NAME' => $this->input->post('SPOUSE_NAME'),
                'SPOUSE_FATHERS_NAME' => $this->input->post('SPOUSE_FATHERS_NAME'),
                'SPOUSE_MOTHERS_NAME' => $this->input->post('SPOUSE_MOTHERS_NAME'),
                'SPOUSE_EMAILID' => $this->input->post('SPOUSE_EMAILID'),
                'SPOUSE_HOME_PHONE' => $this->input->post('SPOUSE_HOME_PHONE'),
                'SPOUSE_HAND_PHONE' => $this->input->post('SPOUSE_HAND_PHONE'),
                'SPOUSE_ADDRESS' => $this->input->post('SPOUSE_ADDRESS'),
                'SPOUSE_DOB' => $this->input->post('SPOUSE_DOB'),
                'SPOUSE_AGE' => $this->input->post('SPOUSE_AGE'),
                'SPOUSE_NO_OF_CHILDREN' => $this->input->post('SPOUSE_NO_OF_CHILDREN'),
                'SPOUSE_GENDER' => $this->input->post('SPOUSE_GENDER'),
                'SPOUSE_RACE_ID' => $this->input->post('SPOUSE_RACE_ID'),
                'SPOUSE_COMPANY_NAME' => $this->input->post('SPOUSE_COMPANY_NAME'),
                'SPOUSE_OCCUPATION_DEPT' => $this->input->post('SPOUSE_OCCUPATION_DEPT'),
                'SPOUSE_YEARS_OF_SERVICE_YEAR' => $this->input->post('SPOUSE_YEARS_OF_SERVICE_YEAR'),
                'SPOUSE_YEARS_OF_SERVICE_MONTH' => $this->input->post('SPOUSE_YEARS_OF_SERVICE_MONTH'),
                'SPOUSE_SALARY' => $this->input->post('SPOUSE_SALARY'),
                'SPOUSE_OFFICE_PHONE1' => $this->input->post('SPOUSE_OFFICE_PHONE1'),
                'SPOUSE_OFFICE_PHONE2' => $this->input->post('SPOUSE_OFFICE_PHONE2'),
                'SPOUSE_OFFICE_ADDRESS' => $this->input->post('SPOUSE_OFFICE_ADDRESS'),
                'GUARANTER_PIC_PATH' => $this->input->post('GUARANTER_PIC_PATH'),
                'GUARANTER_IDNO' => $this->input->post('GUARANTER_IDNO'),
                'GUARANTER_NAME' => $this->input->post('GUARANTER_NAME'),
                'GUARANTER_FATHERS_NAME' => $this->input->post('GUARANTER_FATHERS_NAME'),
                'GUARANTER_MOTHERS_NAME' => $this->input->post('GUARANTER_MOTHERS_NAME'),
                'GUARANTER_EMAILID' => $this->input->post('GUARANTER_EMAILID'),
                'GUARANTER_HOME_PHONE' => $this->input->post('GUARANTER_HOME_PHONE'),
                'GUARANTER_HAND_PHONE' => $this->input->post('GUARANTER_HAND_PHONE'),
                'GUARANTER_ADDRESS' => $this->input->post('GUARANTER_ADDRESS'),
                'GUARANTER_DOB' => $this->input->post('GUARANTER_DOB'),
                'GUARANTER_AGE' => $this->input->post('GUARANTER_AGE'),
                'GUARANTER_NO_OF_CHILDREN' => $this->input->post('GUARANTER_NO_OF_CHILDREN'),
                'GUARANTER_GENDER' => $this->input->post('GUARANTER_GENDER'),
                'GUARANTER_RACE_ID' => $this->input->post('GUARANTER_RACE_ID'),
                'GUARANTER_COMPANY_NAME' => $this->input->post('GUARANTER_COMPANY_NAME'),
                'GUARANTER_OCCUPATION_DEPT' => $this->input->post('GUARANTER_OCCUPATION_DEPT'),
                'GUARANTER_YEARS_OF_SERVICE_YEAR' => $this->input->post('GUARANTER_YEARS_OF_SERVICE_YEAR'),
                'GUARANTER_YEARS_OF_SERVICE_MONTH' => $this->input->post('GUARANTER_YEARS_OF_SERVICE_MONTH'),
                'GUARANTER_SALARY' => $this->input->post('GUARANTER_SALARY'),
                'GUARANTER_OFFICE_PHONE1' => $this->input->post('GUARANTER_OFFICE_PHONE1'),
                'GUARANTER_OFFICE_PHONE2' => $this->input->post('GUARANTER_OFFICE_PHONE2'),
                'GUARANTER_OFFICE_ADDRESS' => $this->input->post('GUARANTER_OFFICE_ADDRESS'),
                'CUSTOMER_POPUP_NOTES' => $this->input->post('CUSTOMER_POPUP_NOTES'),
                'VERIFICATION_HR_INFO' => $this->input->post('VERIFICATION_HR_INFO'),
                'VERIFICATION_SPOUSE_INFO' => $this->input->post('VERIFICATION_SPOUSE_INFO'),
                'VERIFICATION_REFERENCE_INFO' => $this->input->post('VERIFICATION_REFERENCE_INFO'),
                'VERIFICATION_OTHER_INFO' => $this->input->post('VERIFICATION_OTHER_INFO'),
                'VERIFICATION_CTOS_INFO' => $this->input->post('VERIFICATION_CTOS_INFO'),
                'VERIFICATION_CTOS_ATTACHMENT_FILE_PATH' => $this->input->post('VERIFICATION_CTOS_ATTACHMENT_FILE_PATH'),
                'VERIFICATION_COMPLETED' => $this->input->post('VERIFICATION_COMPLETED'),
                'APPLICATION_APPROVED_REJECTED_STATUS' => $this->input->post('APPLICATION_APPROVED_REJECTED_STATUS'),
                'DIRECTOR_NAME2' => $this->input->post('DIRECTOR_NAME2'),
                'DIRECTOR2_OCCUPATION_DEPT_NAME' => $this->input->post('DIRECTOR2_OCCUPATION_DEPT_NAME'),
                'DIRECTOR_NAME3' => $this->input->post('DIRECTOR_NAME3'),
                'DIRECTOR3_OCCUPATION_DEPT_NAME' => $this->input->post('DIRECTOR3_OCCUPATION_DEPT_NAME'),
                'PAID_UP_CAPITAL' => $this->input->post('PAID_UP_CAPITAL'),
                'ORGTYPE_ID' => $this->input->post('ORGTYPE_ID'),
                'VERIFICATION_GUARANTER_INFO' => $this->input->post('VERIFICATION_GUARANTER_INFO'),
                'CREATED_DATE' => $this->input->post('CREATED_DATE'),
                'CREATED_BY' => $this->input->post('CREATED_BY'),
                'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
                'MODIFIED_BY' => $this->input->post('MODIFIED_BY'),
                'CLIENT_ID' => $this->input->post('CLIENT_ID'),
                'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
                'APPROVED_REJECTED_BY_EMP' => $this->input->post('APPROVED_REJECTED_BY_EMP'),
                'APPLICATION_APPROVED_REJECTED_DATE' => $this->input->post('APPLICATION_APPROVED_REJECTED_DATE'),
                'APPLICABLE_AMOUNT' => $this->input->post('APPLICABLE_AMOUNT'),
                'APPLIED_AMOUNT' => $this->input->post('APPLIED_AMOUNT'),
            );

            $customer_detail_id = $this->Customer_detail_model->add_customer_detail($params);
            redirect('customers/customerDetails');
        } else {
            $this->load->model('Masters_agent_info_model');
            $data['all_masters_agent_info'] = $this->Masters_agent_info_model->get_all_masters_agent_info();

            $this->load->model('Masters_advertisement_model');
            $data['all_masters_advertisements'] = $this->Masters_advertisement_model->get_all_masters_advertisements();

            $this->load->model('Administration_comp_profile_model');
            $data['all_administration_comp_profile'] = $this->Administration_comp_profile_model->get_all_administration_comp_profile();

            $this->load->model('Masters_race_model');
            $data['all_masters_race'] = $this->Masters_race_model->get_all_masters_race();

            $this->load->model('Masters_cust_bank_model');
            $data['all_masters_cust_bank'] = $this->Masters_cust_bank_model->get_all_masters_cust_bank();
            $data['all_masters_race'] = $this->Masters_race_model->get_all_masters_race();

            $this->load->model('Masters_cust_comp_info_model');
            $data['all_masters_cust_comp_info'] = $this->Masters_cust_comp_info_model->get_all_masters_cust_comp_info();
            $data['all_masters_race'] = $this->Masters_race_model->get_all_masters_race();
            $data['all_masters_cust_comp_info'] = $this->Masters_cust_comp_info_model->get_all_masters_cust_comp_info();

            // $data['_view'] = 'customer_detail/add';
            $data['_view'] = 'customer_detail/add';
            //echo "<pre/>";print_r($data);exit;
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a customer_detail
     */

    function edit($CUSTOMER_ID) {
        // check if the customer_detail exists before trying to edit it
        $data['customer_detail'] = $this->Customer_detail_model->get_customer_detail($CUSTOMER_ID);

        if (isset($data['customer_detail']['CUSTOMER_ID'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('CUSTOMER_TYPE', 'CUSTOMER TYPE', 'required');
            $this->form_validation->set_rules('CUSTOMER_IDNO', 'CUSTOMER IDNO', 'required');
            $this->form_validation->set_rules('CUSTOMER_NAME', 'CUSTOMER NAME', 'required');
            $this->form_validation->set_rules('EMAIL_ID', 'EMAIL ID', 'required|valid_email');
            $this->form_validation->set_rules('AGE', 'AGE', 'integer');
            $this->form_validation->set_rules('CREDIT_LIMIT', 'CREDIT LIMIT', 'numeric');
            $this->form_validation->set_rules('PRESENT_SALARY', 'PRESENT SALARY', 'numeric');
            $this->form_validation->set_rules('SPOUSE_EMAILID', 'SPOUSE EMAILID', 'valid_email');
            $this->form_validation->set_rules('SPOUSE_HOME_PHONE', 'SPOUSE HOME PHONE', 'integer');
            $this->form_validation->set_rules('SPOUSE_NO_OF_CHILDREN', 'SPOUSE NO OF CHILDREN', 'integer');
            $this->form_validation->set_rules('SPOUSE_AGE', 'SPOUSE AGE', 'integer');
            $this->form_validation->set_rules('GUARANTER_EMAILID', 'GUARANTER EMAILID', 'valid_email');
            $this->form_validation->set_rules('GUARANTER_HOME_PHONE', 'GUARANTER HOME PHONE', 'integer');
            $this->form_validation->set_rules('GUARANTER_HAND_PHONE', 'GUARANTER HAND PHONE', 'integer');
            $this->form_validation->set_rules('GUARANTER_AGE', 'GUARANTER AGE', 'numeric');
            $this->form_validation->set_rules('GUARANTER_NO_OF_CHILDREN', 'GUARANTER NO OF CHILDREN', 'integer');
            $this->form_validation->set_rules('GUARANTER_SALARY', 'GUARANTER SALARY', 'numeric');
            $this->form_validation->set_rules('GUARANTER_OFFICE_PHONE1', 'GUARANTER OFFICE PHONE1', 'integer');
            $this->form_validation->set_rules('GUARANTER_OFFICE_PHONE2', 'GUARANTER OFFICE PHONE2', 'integer');
            $this->form_validation->set_rules('APPLICABLE_AMOUNT', 'APPLICABLE AMOUNT', 'numeric');
            $this->form_validation->set_rules('APPLIED_AMOUNT', 'APPLIED AMOUNT', 'numeric');

            if ($this->form_validation->run()) {
                $params = array(
                    'CUSTOMER_TYPE' => $this->input->post('CUSTOMER_TYPE'),
                    'CUSTOMER_PIC_PATH' => $this->input->post('CUSTOMER_PIC_PATH'),
                    'CUSTOMER_IDNO' => $this->input->post('CUSTOMER_IDNO'),
                    'CUSTOMER_NAME' => $this->input->post('CUSTOMER_NAME'),
                    'FILE_NO' => $this->input->post('FILE_NO'),
                    'OLDIC_NO' => $this->input->post('OLDIC_NO'),
                    'NON_ICNO' => $this->input->post('NON_ICNO'),
                    'APPLICATION_DATE' => $this->input->post('APPLICATION_DATE'),
                    'AGENT_ID' => $this->input->post('AGENT_ID'),
                    'VEHICLE_NO' => $this->input->post('VEHICLE_NO'),
                    'RELATED_TO_EMP' => $this->input->post('RELATED_TO_EMP'),
                    'ADVERTISEMENT_ID' => $this->input->post('ADVERTISEMENT_ID'),
                    'DOB' => $this->input->post('DOB'),
                    'AGE' => $this->input->post('AGE'),
                    'GENDER' => $this->input->post('GENDER'),
                    'HOUSESTATUS_ID' => $this->input->post('HOUSESTATUS_ID'),
                    'MARTIAL_STATUS' => $this->input->post('MARTIAL_STATUS'),
                    'EMAIL_ID' => $this->input->post('EMAIL_ID'),
                    'APPLIED_BRANCH_ID' => $this->input->post('APPLIED_BRANCH_ID'),
                    'COMPANY_ID' => $this->input->post('COMPANY_ID'),
                    'OCCUPATION_DEPT_NAME' => $this->input->post('OCCUPATION_DEPT_NAME'),
                    'RACE_ID' => $this->input->post('RACE_ID'),
                    'PRESENT_SALARY' => $this->input->post('PRESENT_SALARY'),
                    'JOBSECTOR_ID' => $this->input->post('JOBSECTOR_ID'),
                    'YEARS_OR_SERVICE_YEARS' => $this->input->post('YEARS_OR_SERVICE_YEARS'),
                    'YEARS_OR_SERVICE_MONTHS' => $this->input->post('YEARS_OR_SERVICE_MONTHS'),
                    'CREDIT_LIMIT' => $this->input->post('CREDIT_LIMIT'),
                    'BANK_ID' => $this->input->post('BANK_ID'),
                    'BANK_ACCOUNTNO' => $this->input->post('BANK_ACCOUNTNO'),
                    'BANK_ATM_CARD_NO' => $this->input->post('BANK_ATM_CARD_NO'),
                    'BANK_ATM_CARD_PIN_NO' => $this->input->post('BANK_ATM_CARD_PIN_NO'),
                    'BANK_ATM_CARD_VALIDITY' => $this->input->post('BANK_ATM_CARD_VALIDITY'),
                    'INTERNET_BANKING_USER_NAME' => $this->input->post('INTERNET_BANKING_USER_NAME'),
                    'INTERNET_BANKING_PASSWORD' => $this->input->post('INTERNET_BANKING_PASSWORD'),
                    'MONEY_DEPOSIT_BANK_ID' => $this->input->post('MONEY_DEPOSIT_BANK_ID'),
                    'MONEY_DEPOSIT_ACCOUNT_NO' => $this->input->post('MONEY_DEPOSIT_ACCOUNT_NO'),
                    'MONEY_DEPOSIT_ACCOUNT_HOLDER_NAME' => $this->input->post('MONEY_DEPOSIT_ACCOUNT_HOLDER_NAME'),
                    'SPOUSE_PIC_PATH' => $this->input->post('SPOUSE_PIC_PATH'),
                    'SPOUSE_IDNO' => $this->input->post('SPOUSE_IDNO'),
                    'SPOUSE_NAME' => $this->input->post('SPOUSE_NAME'),
                    'SPOUSE_FATHERS_NAME' => $this->input->post('SPOUSE_FATHERS_NAME'),
                    'SPOUSE_MOTHERS_NAME' => $this->input->post('SPOUSE_MOTHERS_NAME'),
                    'SPOUSE_EMAILID' => $this->input->post('SPOUSE_EMAILID'),
                    'SPOUSE_HOME_PHONE' => $this->input->post('SPOUSE_HOME_PHONE'),
                    'SPOUSE_HAND_PHONE' => $this->input->post('SPOUSE_HAND_PHONE'),
                    'SPOUSE_ADDRESS' => $this->input->post('SPOUSE_ADDRESS'),
                    'SPOUSE_DOB' => $this->input->post('SPOUSE_DOB'),
                    'SPOUSE_AGE' => $this->input->post('SPOUSE_AGE'),
                    'SPOUSE_NO_OF_CHILDREN' => $this->input->post('SPOUSE_NO_OF_CHILDREN'),
                    'SPOUSE_GENDER' => $this->input->post('SPOUSE_GENDER'),
                    'SPOUSE_RACE_ID' => $this->input->post('SPOUSE_RACE_ID'),
                    'SPOUSE_COMPANY_NAME' => $this->input->post('SPOUSE_COMPANY_NAME'),
                    'SPOUSE_OCCUPATION_DEPT' => $this->input->post('SPOUSE_OCCUPATION_DEPT'),
                    'SPOUSE_YEARS_OF_SERVICE_YEAR' => $this->input->post('SPOUSE_YEARS_OF_SERVICE_YEAR'),
                    'SPOUSE_YEARS_OF_SERVICE_MONTH' => $this->input->post('SPOUSE_YEARS_OF_SERVICE_MONTH'),
                    'SPOUSE_SALARY' => $this->input->post('SPOUSE_SALARY'),
                    'SPOUSE_OFFICE_PHONE1' => $this->input->post('SPOUSE_OFFICE_PHONE1'),
                    'SPOUSE_OFFICE_PHONE2' => $this->input->post('SPOUSE_OFFICE_PHONE2'),
                    'SPOUSE_OFFICE_ADDRESS' => $this->input->post('SPOUSE_OFFICE_ADDRESS'),
                    'GUARANTER_PIC_PATH' => $this->input->post('GUARANTER_PIC_PATH'),
                    'GUARANTER_IDNO' => $this->input->post('GUARANTER_IDNO'),
                    'GUARANTER_NAME' => $this->input->post('GUARANTER_NAME'),
                    'GUARANTER_FATHERS_NAME' => $this->input->post('GUARANTER_FATHERS_NAME'),
                    'GUARANTER_MOTHERS_NAME' => $this->input->post('GUARANTER_MOTHERS_NAME'),
                    'GUARANTER_EMAILID' => $this->input->post('GUARANTER_EMAILID'),
                    'GUARANTER_HOME_PHONE' => $this->input->post('GUARANTER_HOME_PHONE'),
                    'GUARANTER_HAND_PHONE' => $this->input->post('GUARANTER_HAND_PHONE'),
                    'GUARANTER_ADDRESS' => $this->input->post('GUARANTER_ADDRESS'),
                    'GUARANTER_DOB' => $this->input->post('GUARANTER_DOB'),
                    'GUARANTER_AGE' => $this->input->post('GUARANTER_AGE'),
                    'GUARANTER_NO_OF_CHILDREN' => $this->input->post('GUARANTER_NO_OF_CHILDREN'),
                    'GUARANTER_GENDER' => $this->input->post('GUARANTER_GENDER'),
                    'GUARANTER_RACE_ID' => $this->input->post('GUARANTER_RACE_ID'),
                    'GUARANTER_COMPANY_NAME' => $this->input->post('GUARANTER_COMPANY_NAME'),
                    'GUARANTER_OCCUPATION_DEPT' => $this->input->post('GUARANTER_OCCUPATION_DEPT'),
                    'GUARANTER_YEARS_OF_SERVICE_YEAR' => $this->input->post('GUARANTER_YEARS_OF_SERVICE_YEAR'),
                    'GUARANTER_YEARS_OF_SERVICE_MONTH' => $this->input->post('GUARANTER_YEARS_OF_SERVICE_MONTH'),
                    'GUARANTER_SALARY' => $this->input->post('GUARANTER_SALARY'),
                    'GUARANTER_OFFICE_PHONE1' => $this->input->post('GUARANTER_OFFICE_PHONE1'),
                    'GUARANTER_OFFICE_PHONE2' => $this->input->post('GUARANTER_OFFICE_PHONE2'),
                    'GUARANTER_OFFICE_ADDRESS' => $this->input->post('GUARANTER_OFFICE_ADDRESS'),
                    'CUSTOMER_POPUP_NOTES' => $this->input->post('CUSTOMER_POPUP_NOTES'),
                    'VERIFICATION_HR_INFO' => $this->input->post('VERIFICATION_HR_INFO'),
                    'VERIFICATION_SPOUSE_INFO' => $this->input->post('VERIFICATION_SPOUSE_INFO'),
                    'VERIFICATION_REFERENCE_INFO' => $this->input->post('VERIFICATION_REFERENCE_INFO'),
                    'VERIFICATION_OTHER_INFO' => $this->input->post('VERIFICATION_OTHER_INFO'),
                    'VERIFICATION_CTOS_INFO' => $this->input->post('VERIFICATION_CTOS_INFO'),
                    'VERIFICATION_CTOS_ATTACHMENT_FILE_PATH' => $this->input->post('VERIFICATION_CTOS_ATTACHMENT_FILE_PATH'),
                    'VERIFICATION_COMPLETED' => $this->input->post('VERIFICATION_COMPLETED'),
                    'APPLICATION_APPROVED_REJECTED_STATUS' => $this->input->post('APPLICATION_APPROVED_REJECTED_STATUS'),
                    'DIRECTOR_NAME2' => $this->input->post('DIRECTOR_NAME2'),
                    'DIRECTOR2_OCCUPATION_DEPT_NAME' => $this->input->post('DIRECTOR2_OCCUPATION_DEPT_NAME'),
                    'DIRECTOR_NAME3' => $this->input->post('DIRECTOR_NAME3'),
                    'DIRECTOR3_OCCUPATION_DEPT_NAME' => $this->input->post('DIRECTOR3_OCCUPATION_DEPT_NAME'),
                    'PAID_UP_CAPITAL' => $this->input->post('PAID_UP_CAPITAL'),
                    'ORGTYPE_ID' => $this->input->post('ORGTYPE_ID'),
                    'VERIFICATION_GUARANTER_INFO' => $this->input->post('VERIFICATION_GUARANTER_INFO'),
                    'CREATED_DATE' => $this->input->post('CREATED_DATE'),
                    'CREATED_BY' => $this->input->post('CREATED_BY'),
                    'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
                    'MODIFIED_BY' => $this->input->post('MODIFIED_BY'),
                    'CLIENT_ID' => $this->input->post('CLIENT_ID'),
                    'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
                    'APPROVED_REJECTED_BY_EMP' => $this->input->post('APPROVED_REJECTED_BY_EMP'),
                    'APPLICATION_APPROVED_REJECTED_DATE' => $this->input->post('APPLICATION_APPROVED_REJECTED_DATE'),
                    'APPLICABLE_AMOUNT' => $this->input->post('APPLICABLE_AMOUNT'),
                    'APPLIED_AMOUNT' => $this->input->post('APPLIED_AMOUNT'),
                );

                $this->Customer_detail_model->update_customer_detail($CUSTOMER_ID, $params);
                redirect('customer_detail/index');
            } else {
                $this->load->model('Masters_agent_info_model');
                $data['all_masters_agent_info'] = $this->Masters_agent_info_model->get_all_masters_agent_info();

                $this->load->model('Masters_advertisement_model');
                $data['all_masters_advertisements'] = $this->Masters_advertisement_model->get_all_masters_advertisements();

                $this->load->model('Administration_comp_profile_model');
                $data['all_administration_comp_profile'] = $this->Administration_comp_profile_model->get_all_administration_comp_profile();

                $this->load->model('Masters_race_model');
                $data['all_masters_race'] = $this->Masters_race_model->get_all_masters_race();

                $this->load->model('Masters_cust_bank_model');
                $data['all_masters_cust_bank'] = $this->Masters_cust_bank_model->get_all_masters_cust_bank();
                $data['all_masters_race'] = $this->Masters_race_model->get_all_masters_race();

                $this->load->model('Masters_cust_comp_info_model');
                $data['all_masters_cust_comp_info'] = $this->Masters_cust_comp_info_model->get_all_masters_cust_comp_info();
                $data['all_masters_race'] = $this->Masters_race_model->get_all_masters_race();
                $data['all_masters_cust_comp_info'] = $this->Masters_cust_comp_info_model->get_all_masters_cust_comp_info();

                $data['_view'] = 'customer_detail/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The customer_detail you are trying to edit does not exist.');
    }

    /*
     * Deleting customer_detail
     */

    function remove($CUSTOMER_ID) {
        $customer_detail = $this->Customer_detail_model->get_customer_detail($CUSTOMER_ID);

        // check if the customer_detail exists before trying to delete it
        if (isset($customer_detail['CUSTOMER_ID'])) {
            $this->Customer_detail_model->delete_customer_detail($CUSTOMER_ID);
            redirect('customer_detail/index');
        } else
            show_error('The customer_detail you are trying to delete does not exist.');
    }

}
