<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Masters_cust_bank extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Masters_cust_bank_model');
        $this->load->model('Client_info_model');
    }

    /*
     * Listing of masters_cust_bank
     */

    function index() {
        $data['masters_cust_bank'] = $this->Masters_cust_bank_model->get_all_masters_cust_bank();

        $data['_view'] = 'masters_cust_bank/index';
        $this->load->view('layouts/main', $data);
    }

    /**
     * Function to get all masters cut bak data
     * 
     * @return json result
     */
    function getAllMastersCustBank() {
        $request = $_GET;
        $result = $this->Masters_cust_bank_model->getAllMastersCustBankData($request, array());
        echo json_encode($result);
        exit;
    }

    /*
     * Adding a new masters_cust_bank
     */

    function add() {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('BANK_CODE', 'BANK CODE', 'required');
        $this->form_validation->set_rules('BANK_NAME', 'BANK NAME', 'required');

        if ($this->form_validation->run()) {
            $params = array(
                'BANK_CODE' => $this->input->post('BANK_CODE'),
                'BANK_NAME' => $this->input->post('BANK_NAME'),
                'BANK_BRANCH' => $this->input->post('BANK_BRANCH'),
                'CREATED_DATE' => date("Y-m-d H:i:s"),
                'CREATED_BY' => $this->session->userdata['user']['LOGIN_ID'],
                'IS_ACTIVE' => 1,
            );

            $masters_cust_bank_id = $this->Masters_cust_bank_model->add_masters_cust_bank($params);
            redirect('masters_cust_bank/index');
        } else {
            $data['all_client_info'] = $this->Client_info_model->get_all_client_info();
            $data['_view'] = 'masters_cust_bank/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a masters_cust_bank
     */

    function edit($BANK_ID) {
        // check if the masters_cust_bank exists before trying to edit it
        $data['masters_cust_bank'] = $this->Masters_cust_bank_model->get_masters_cust_bank($BANK_ID);

        if (isset($data['masters_cust_bank']['BANK_ID'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('BANK_CODE', 'BANK CODE', 'required');
            $this->form_validation->set_rules('BANK_NAME', 'BANK NAME', 'required');

            if ($this->form_validation->run()) {
                $params = array(
                    'BANK_CODE' => $this->input->post('BANK_CODE'),
                    'BANK_NAME' => $this->input->post('BANK_NAME'),
                    'BANK_BRANCH' => $this->input->post('BANK_BRANCH'),
                    'MODIFIED_DATE' => date("Y-m-d H:i:s"),
                    'MODIFIED_BY' => $this->session->userdata['user']['LOGIN_ID'],
                    'IS_ACTIVE' => 1,
                );

                $this->Masters_cust_bank_model->update_masters_cust_bank($BANK_ID, $params);
                redirect('masters_cust_bank/index');
            } else {
                $data['all_client_info'] = $this->Client_info_model->get_all_client_info();
                $data['_view'] = 'masters_cust_bank/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The masters_cust_bank you are trying to edit does not exist.');
    }

    /*
     * Deleting masters_cust_bank
     */

    function remove($BANK_ID) {
        $masters_cust_bank = $this->Masters_cust_bank_model->get_masters_cust_bank($BANK_ID);

        // check if the masters_cust_bank exists before trying to delete it
        if (isset($masters_cust_bank['BANK_ID'])) {
            $this->Masters_cust_bank_model->delete_masters_cust_bank($BANK_ID);
            redirect('masters_cust_bank/index');
        } else
            show_error('The masters_cust_bank you are trying to delete does not exist.');
    }

}
