<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Masters_ornament extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Masters_ornament_model');
    } 

    /*
     * Listing of masters_ornaments
     */
    function index()
    {
        $data['masters_ornaments'] = $this->Masters_ornament_model->get_all_masters_ornaments();

        $data['_view'] = 'masters_ornament/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new masters_ornament
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'ORNAMENT_NAME' => $this->input->post('ORNAMENT_NAME'),
				'CREATED_DATE' => $this->input->post('CREATED_DATE'),
				'CREATED_BY' => $this->input->post('CREATED_BY'),
				'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
				'MODIFIED_BY' => $this->input->post('MODIFIED_BY'),
				'CLIENT_ID' => $this->input->post('CLIENT_ID'),
				'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
            );
            
            $masters_ornament_id = $this->Masters_ornament_model->add_masters_ornament($params);
            redirect('masters_ornament/index');
        }
        else
        {            
            $data['_view'] = 'masters_ornament/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a masters_ornament
     */
    function edit($ORNAMENT_ID)
    {   
        // check if the masters_ornament exists before trying to edit it
        $data['masters_ornament'] = $this->Masters_ornament_model->get_masters_ornament($ORNAMENT_ID);
        
        if(isset($data['masters_ornament']['ORNAMENT_ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'ORNAMENT_NAME' => $this->input->post('ORNAMENT_NAME'),
					'CREATED_DATE' => $this->input->post('CREATED_DATE'),
					'CREATED_BY' => $this->input->post('CREATED_BY'),
					'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
					'MODIFIED_BY' => $this->input->post('MODIFIED_BY'),
					'CLIENT_ID' => $this->input->post('CLIENT_ID'),
					'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
                );

                $this->Masters_ornament_model->update_masters_ornament($ORNAMENT_ID,$params);            
                redirect('masters_ornament/index');
            }
            else
            {
                $data['_view'] = 'masters_ornament/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The masters_ornament you are trying to edit does not exist.');
    } 

    /*
     * Deleting masters_ornament
     */
    function remove($ORNAMENT_ID)
    {
        $masters_ornament = $this->Masters_ornament_model->get_masters_ornament($ORNAMENT_ID);

        // check if the masters_ornament exists before trying to delete it
        if(isset($masters_ornament['ORNAMENT_ID']))
        {
            $this->Masters_ornament_model->delete_masters_ornament($ORNAMENT_ID);
            redirect('masters_ornament/index');
        }
        else
            show_error('The masters_ornament you are trying to delete does not exist.');
    }
    
}
