<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Masters_jobsector extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Masters_jobsector_model');
        $this->load->model('Client_info_model');
    }

    /*
     * Listing of masters_jobsector
     */

    function index() {
        $data['masters_jobsector'] = $this->Masters_jobsector_model->get_all_masters_jobsector();

        $data['_view'] = 'masters_jobsector/index';
        $this->load->view('layouts/main', $data);
    }

    /**
     * Function to get all masters job sector data
     * 
     * @return json result
     */
    function getAllMastersJobSector() {
        $request = $_GET;
        $result = $this->Masters_jobsector_model->getAllMastersJobSectorData($request, array());
        echo json_encode($result);
        exit;
    }

    /*
     * Adding a new masters_jobsector
     */

    function add() {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'JOBSECTOR_NAME' => $this->input->post('JOBSECTOR_NAME'),
                'LOAN_TYPE' => $this->input->post('LOAN_TYPE'),
                'CREATED_DATE' => date("Y-m-d H:i:s"),
                'CREATED_BY' => $this->session->userdata['user']['LOGIN_ID'],
                'CLIENT_ID' => $this->input->post('CLIENT_ID'),
                'IS_ACTIVE' => 1,
            );

            $masters_jobsector_id = $this->Masters_jobsector_model->add_masters_jobsector($params);
            redirect('masters_jobsector/index');
        } else {
            $data['all_client_info'] = $this->Client_info_model->get_all_client_info();
            $data['_view'] = 'masters_jobsector/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a masters_jobsector
     */

    function edit($JOBSECTOR_ID) {
        // check if the masters_jobsector exists before trying to edit it
        $data['masters_jobsector'] = $this->Masters_jobsector_model->get_masters_jobsector($JOBSECTOR_ID);

        if (isset($data['masters_jobsector']['JOBSECTOR_ID'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'JOBSECTOR_NAME' => $this->input->post('JOBSECTOR_NAME'),
                    'LOAN_TYPE' => $this->input->post('LOAN_TYPE'),
                    'MODIFIED_DATE' => date("Y-m-d H:i:s"),
                    'MODIFIED_BY' => $this->session->userdata['user']['LOGIN_ID'],
                    'CLIENT_ID' => $this->input->post('CLIENT_ID'),
                    'IS_ACTIVE' => 1,
                );

                $this->Masters_jobsector_model->update_masters_jobsector($JOBSECTOR_ID, $params);
                redirect('masters_jobsector/index');
            } else {
                $data['all_client_info'] = $this->Client_info_model->get_all_client_info();
                $data['_view'] = 'masters_jobsector/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The masters_jobsector you are trying to edit does not exist.');
    }

    /*
     * Deleting masters_jobsector
     */

    function remove($JOBSECTOR_ID) {
        $masters_jobsector = $this->Masters_jobsector_model->get_masters_jobsector($JOBSECTOR_ID);

        // check if the masters_jobsector exists before trying to delete it
        if (isset($masters_jobsector['JOBSECTOR_ID'])) {
            $this->Masters_jobsector_model->delete_masters_jobsector($JOBSECTOR_ID);
            redirect('masters_jobsector/index');
        } else
            show_error('The masters_jobsector you are trying to delete does not exist.');
    }

}
