<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Masters_housestatu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Masters_housestatu_model');
    } 

    /*
     * Listing of masters_housestatus
     */
    function index()
    {
        $data['masters_housestatus'] = $this->Masters_housestatu_model->get_all_masters_housestatus();

        $data['_view'] = 'masters_housestatu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new masters_housestatu
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'HOUSESTATUS_NAME' => $this->input->post('HOUSESTATUS_NAME'),
				'CREATED_DATE' => $this->input->post('CREATED_DATE'),
				'CREATED_BY' => $this->input->post('CREATED_BY'),
				'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
				'MODIFIED_BY' => $this->input->post('MODIFIED_BY'),
				'CLIENT_ID' => $this->input->post('CLIENT_ID'),
				'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
            );
            
            $masters_housestatu_id = $this->Masters_housestatu_model->add_masters_housestatu($params);
            redirect('masters_housestatu/index');
        }
        else
        {            
            $data['_view'] = 'masters_housestatu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a masters_housestatu
     */
    function edit($HOUSESTATUS_ID)
    {   
        // check if the masters_housestatu exists before trying to edit it
        $data['masters_housestatu'] = $this->Masters_housestatu_model->get_masters_housestatu($HOUSESTATUS_ID);
        
        if(isset($data['masters_housestatu']['HOUSESTATUS_ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'HOUSESTATUS_NAME' => $this->input->post('HOUSESTATUS_NAME'),
					'CREATED_DATE' => $this->input->post('CREATED_DATE'),
					'CREATED_BY' => $this->input->post('CREATED_BY'),
					'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
					'MODIFIED_BY' => $this->input->post('MODIFIED_BY'),
					'CLIENT_ID' => $this->input->post('CLIENT_ID'),
					'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
                );

                $this->Masters_housestatu_model->update_masters_housestatu($HOUSESTATUS_ID,$params);            
                redirect('masters_housestatu/index');
            }
            else
            {
                $data['_view'] = 'masters_housestatu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The masters_housestatu you are trying to edit does not exist.');
    } 

    /*
     * Deleting masters_housestatu
     */
    function remove($HOUSESTATUS_ID)
    {
        $masters_housestatu = $this->Masters_housestatu_model->get_masters_housestatu($HOUSESTATUS_ID);

        // check if the masters_housestatu exists before trying to delete it
        if(isset($masters_housestatu['HOUSESTATUS_ID']))
        {
            $this->Masters_housestatu_model->delete_masters_housestatu($HOUSESTATUS_ID);
            redirect('masters_housestatu/index');
        }
        else
            show_error('The masters_housestatu you are trying to delete does not exist.');
    }
    
}
