<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Masters_orgtype extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Masters_orgtype_model');
    } 

    /*
     * Listing of masters_orgtype
     */
    function index()
    {
        $data['masters_orgtype'] = $this->Masters_orgtype_model->get_all_masters_orgtype();

        $data['_view'] = 'masters_orgtype/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new masters_orgtype
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'ORGTYPE_NAME' => $this->input->post('ORGTYPE_NAME'),
				'CREATED_DATE' => $this->input->post('CREATED_DATE'),
				'CREATED_BY' => $this->input->post('CREATED_BY'),
				'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
				'MODIFIED_BY' => $this->input->post('MODIFIED_BY'),
				'CLIENT_ID' => $this->input->post('CLIENT_ID'),
				'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
            );
            
            $masters_orgtype_id = $this->Masters_orgtype_model->add_masters_orgtype($params);
            redirect('masters_orgtype/index');
        }
        else
        {            
            $data['_view'] = 'masters_orgtype/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a masters_orgtype
     */
    function edit($ORGTYPE_ID)
    {   
        // check if the masters_orgtype exists before trying to edit it
        $data['masters_orgtype'] = $this->Masters_orgtype_model->get_masters_orgtype($ORGTYPE_ID);
        
        if(isset($data['masters_orgtype']['ORGTYPE_ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'ORGTYPE_NAME' => $this->input->post('ORGTYPE_NAME'),
					'CREATED_DATE' => $this->input->post('CREATED_DATE'),
					'CREATED_BY' => $this->input->post('CREATED_BY'),
					'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
					'MODIFIED_BY' => $this->input->post('MODIFIED_BY'),
					'CLIENT_ID' => $this->input->post('CLIENT_ID'),
					'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
                );

                $this->Masters_orgtype_model->update_masters_orgtype($ORGTYPE_ID,$params);            
                redirect('masters_orgtype/index');
            }
            else
            {
                $data['_view'] = 'masters_orgtype/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The masters_orgtype you are trying to edit does not exist.');
    } 

    /*
     * Deleting masters_orgtype
     */
    function remove($ORGTYPE_ID)
    {
        $masters_orgtype = $this->Masters_orgtype_model->get_masters_orgtype($ORGTYPE_ID);

        // check if the masters_orgtype exists before trying to delete it
        if(isset($masters_orgtype['ORGTYPE_ID']))
        {
            $this->Masters_orgtype_model->delete_masters_orgtype($ORGTYPE_ID);
            redirect('masters_orgtype/index');
        }
        else
            show_error('The masters_orgtype you are trying to delete does not exist.');
    }
    
}
