<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Masters_carat extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Masters_carat_model');
    } 

    /*
     * Listing of masters_carat
     */
    function index()
    {
        $data['masters_carat'] = $this->Masters_carat_model->get_all_masters_carat();

        $data['_view'] = 'masters_carat/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new masters_carat
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'CARAT_NAME' => $this->input->post('CARAT_NAME'),
				'CREATED_DATE' => $this->input->post('CREATED_DATE'),
				'CREATED_BY' => $this->input->post('CREATED_BY'),
				'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
				'MODIFIED_BY' => $this->input->post('MODIFIED_BY'),
				'CLIENT_ID' => $this->input->post('CLIENT_ID'),
				'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
            );
            
            $masters_carat_id = $this->Masters_carat_model->add_masters_carat($params);
            redirect('masters_carat/index');
        }
        else
        {            
            $data['_view'] = 'masters_carat/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a masters_carat
     */
    function edit($CARAT_ID)
    {   
        // check if the masters_carat exists before trying to edit it
        $data['masters_carat'] = $this->Masters_carat_model->get_masters_carat($CARAT_ID);
        
        if(isset($data['masters_carat']['CARAT_ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'CARAT_NAME' => $this->input->post('CARAT_NAME'),
					'CREATED_DATE' => $this->input->post('CREATED_DATE'),
					'CREATED_BY' => $this->input->post('CREATED_BY'),
					'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
					'MODIFIED_BY' => $this->input->post('MODIFIED_BY'),
					'CLIENT_ID' => $this->input->post('CLIENT_ID'),
					'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
                );

                $this->Masters_carat_model->update_masters_carat($CARAT_ID,$params);            
                redirect('masters_carat/index');
            }
            else
            {
                $data['_view'] = 'masters_carat/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The masters_carat you are trying to edit does not exist.');
    } 

    /*
     * Deleting masters_carat
     */
    function remove($CARAT_ID)
    {
        $masters_carat = $this->Masters_carat_model->get_masters_carat($CARAT_ID);

        // check if the masters_carat exists before trying to delete it
        if(isset($masters_carat['CARAT_ID']))
        {
            $this->Masters_carat_model->delete_masters_carat($CARAT_ID);
            redirect('masters_carat/index');
        }
        else
            show_error('The masters_carat you are trying to delete does not exist.');
    }
    
}
