<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Masters_orgtype extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Masters_orgtype_model');
        $this->load->model('Client_info_model');
        $session_data = (isset($this->session->userdata['EMP_DATA']) && !empty($this->session->userdata['EMP_DATA'])) ? $this->session->userdata['EMP_DATA'] : array();
        if (empty($session_data))
            redirect("login");
    }

    /*
     * Listing of masters_orgtype
     */

    function index() {
        $data['masters_orgtype'] = $this->Masters_orgtype_model->get_all_masters_orgtype();

        $data['_view'] = 'masters_orgtype/index';
        $this->load->view('layouts/main', $data);
    }

    function getAllMastersOrgtype() {
        $request = $_GET;
        $result = $this->Masters_orgtype_model->getAllMastersOrgtypeData($request, array());
        echo json_encode($result);
        exit;
    }

    /*
     * Adding a new masters_orgtype
     */

    function add() {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'ORGTYPE_NAME' => $this->input->post('ORGTYPE_NAME'),
                'CREATED_DATE' => date("Y-m-d H:i:s"),
                'CREATED_BY' => $this->session->userdata['EMP_DATA']['EMP_ID'],
                'IS_ACTIVE' => 1,
            );

            $masters_orgtype_id = $this->Masters_orgtype_model->add_masters_orgtype($params);
            redirect('masters_orgtype/index');
        } else {
            $data['all_client_info'] = $this->Client_info_model->get_all_client_info();
            $data['_view'] = 'masters_orgtype/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a masters_orgtype
     */

    function edit($ORGTYPE_ID) {
        // check if the masters_orgtype exists before trying to edit it
        $data['masters_orgtype'] = $this->Masters_orgtype_model->get_masters_orgtype($ORGTYPE_ID);

        if (isset($data['masters_orgtype']['ORGTYPE_ID'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'ORGTYPE_NAME' => $this->input->post('ORGTYPE_NAME'),
                    'MODIFIED_DATE' => date("Y-m-d H:i:s"),
                    'MODIFIED_BY' => $this->session->userdata['EMP_DATA']['EMP_ID'],
                    'IS_ACTIVE' => 1,
                );

                $this->Masters_orgtype_model->update_masters_orgtype($ORGTYPE_ID, $params);
                redirect('masters_orgtype/index');
            } else {
                $data['all_client_info'] = $this->Client_info_model->get_all_client_info();
                $data['_view'] = 'masters_orgtype/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The masters_orgtype you are trying to edit does not exist.');
    }

    /*
     * Deleting masters_orgtype
     */

    function remove($ORGTYPE_ID) {
        $masters_orgtype = $this->Masters_orgtype_model->get_masters_orgtype($ORGTYPE_ID);

        // check if the masters_orgtype exists before trying to delete it
        if (isset($masters_orgtype['ORGTYPE_ID'])) {
            $this->Masters_orgtype_model->delete_masters_orgtype($ORGTYPE_ID);
            redirect('masters_orgtype/index');
        } else
            show_error('The masters_orgtype you are trying to delete does not exist.');
    }

}
