<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Masters_ornament extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Masters_ornament_model');
        $this->load->model('Client_info_model');
    }

    /*
     * Listing of masters_ornaments
     */

    function index() {
        $data['masters_ornaments'] = $this->Masters_ornament_model->get_all_masters_ornaments();

        $data['_view'] = 'masters_ornament/index';
        $this->load->view('layouts/main', $data);
    }

    /**
     * Function to get all masters customer company info
     * 
     * @return json result
     */
    function getAllMastersOrnaments() {
        $request = $_GET;
        $result = $this->Masters_ornament_model->getAllMastersOrnamentsData($request, array());
        echo json_encode($result);
        exit;
    }

    /*
     * Adding a new masters_ornament
     */

    function add() {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'ORNAMENT_NAME' => $this->input->post('ORNAMENT_NAME'),
                'CREATED_DATE' => date("Y-m-d H:i:s"),
                'CREATED_BY' => $this->session->userdata['EMP_DATA']['EMP_ID'],
                'IS_ACTIVE' => 1,
            );

            $masters_ornament_id = $this->Masters_ornament_model->add_masters_ornament($params);
            redirect('masters_ornament/index');
        } else {
            $data['all_client_info'] = $this->Client_info_model->get_all_client_info();
            $data['_view'] = 'masters_ornament/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a masters_ornament
     */

    function edit($ORNAMENT_ID) {
        // check if the masters_ornament exists before trying to edit it
        $data['masters_ornament'] = $this->Masters_ornament_model->get_masters_ornament($ORNAMENT_ID);

        if (isset($data['masters_ornament']['ORNAMENT_ID'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'ORNAMENT_NAME' => $this->input->post('ORNAMENT_NAME'),
                    'MODIFIED_DATE' => date("Y-m-d H:i:s"),
                    'MODIFIED_BY' => $this->session->userdata['EMP_DATA']['EMP_ID'],
                    'IS_ACTIVE' => 1,
                );

                $this->Masters_ornament_model->update_masters_ornament($ORNAMENT_ID, $params);
                redirect('masters_ornament/index');
            } else {
                $data['all_client_info'] = $this->Client_info_model->get_all_client_info();
                $data['_view'] = 'masters_ornament/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The masters_ornament you are trying to edit does not exist.');
    }

    /*
     * Deleting masters_ornament
     */

    function remove($ORNAMENT_ID) {
        $masters_ornament = $this->Masters_ornament_model->get_masters_ornament($ORNAMENT_ID);

        // check if the masters_ornament exists before trying to delete it
        if (isset($masters_ornament['ORNAMENT_ID'])) {
            $this->Masters_ornament_model->delete_masters_ornament($ORNAMENT_ID);
            redirect('masters_ornament/index');
        } else
            show_error('The masters_ornament you are trying to delete does not exist.');
    }

}
