<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Masters_daily_gold_price extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Masters_daily_gold_price_model');
        $this->load->model('Client_info_model');
    }

    /*
     * Listing of masters_daily_gold_price
     */

    function index() {
        $data['masters_daily_gold_price'] = $this->Masters_daily_gold_price_model->get_all_masters_daily_gold_price();

        $data['_view'] = 'masters_daily_gold_price/index';
        $this->load->view('layouts/main', $data);
    }

    /**
     * Function to get all masters daily gold price
     * 
     * @return json result
     */
    function getAllMastesDailyGoldPrice() {
        $request = $_GET;
        $result = $this->Masters_daily_gold_price_model->getAllMastersDailyGoldPriceData($request, array());
        echo json_encode($result);
        exit;
    }

    /*
     * Adding a new masters_daily_gold_price
     */

    function add() {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'CARAT_ID' => $this->input->post('CARAT_ID'),
                'GOLD_PRICE_DATE' => $this->input->post('GOLD_PRICE_DATE'),
                'GOLD_PRICE' => $this->input->post('GOLD_PRICE'),
                'GOLD_PRICE_FACTOR' => $this->input->post('GOLD_PRICE_FACTOR'),
                'GOLD_PRICE_BASIS' => $this->input->post('GOLD_PRICE_BASIS'),
                'CREATED_DATE' => date("Y-m-d H:i:s"),
                'CREATED_BY' => $this->session->userdata['user']['LOGIN_ID'],
                'IS_ACTIVE' => 1,
            );

            $masters_daily_gold_price_id = $this->Masters_daily_gold_price_model->add_masters_daily_gold_price($params);
            redirect('masters_daily_gold_price/index');
        } else {
            $data['all_client_info'] = $this->Client_info_model->get_all_client_info();
            $data['_view'] = 'masters_daily_gold_price/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a masters_daily_gold_price
     */

    function edit($GOLD_PRICE_ID) {
        // check if the masters_daily_gold_price exists before trying to edit it
        $data['masters_daily_gold_price'] = $this->Masters_daily_gold_price_model->get_masters_daily_gold_price($GOLD_PRICE_ID);

        if (isset($data['masters_daily_gold_price']['GOLD_PRICE_ID'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'CARAT_ID' => $this->input->post('CARAT_ID'),
                    'GOLD_PRICE_DATE' => $this->input->post('GOLD_PRICE_DATE'),
                    'GOLD_PRICE' => $this->input->post('GOLD_PRICE'),
                    'GOLD_PRICE_FACTOR' => $this->input->post('GOLD_PRICE_FACTOR'),
                    'GOLD_PRICE_BASIS' => $this->input->post('GOLD_PRICE_BASIS'),
                    'MODIFIED_DATE' => date("Y-m-d H:i:s"),
                    'MODIFIED_BY' => $this->session->userdata['user']['LOGIN_ID'],
                    'IS_ACTIVE' => 1,
                );

                $this->Masters_daily_gold_price_model->update_masters_daily_gold_price($GOLD_PRICE_ID, $params);
                redirect('masters_daily_gold_price/index');
            } else {
                $data['all_client_info'] = $this->Client_info_model->get_all_client_info();
                $data['_view'] = 'masters_daily_gold_price/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The masters_daily_gold_price you are trying to edit does not exist.');
    }

    /*
     * Deleting masters_daily_gold_price
     */

    function remove($GOLD_PRICE_ID) {
        $masters_daily_gold_price = $this->Masters_daily_gold_price_model->get_masters_daily_gold_price($GOLD_PRICE_ID);

        // check if the masters_daily_gold_price exists before trying to delete it
        if (isset($masters_daily_gold_price['GOLD_PRICE_ID'])) {
            $this->Masters_daily_gold_price_model->delete_masters_daily_gold_price($GOLD_PRICE_ID);
            redirect('masters_daily_gold_price/index');
        } else
            show_error('The masters_daily_gold_price you are trying to delete does not exist.');
    }

}
