<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Module extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Module_model');
    } 

    /*
     * Listing of modules
     */
    function index()
    {
        $data['modules'] = $this->Module_model->get_all_modules();

        $data['_view'] = 'module/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new module
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'MODULE_NAME' => $this->input->post('MODULE_NAME'),
				'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
				'CREATED_DATE' => $this->input->post('CREATED_DATE'),
				'CREATED_BY' => $this->input->post('CREATED_BY'),
            );
            
            $module_id = $this->Module_model->add_module($params);
            redirect('module/index');
        }
        else
        {            
            $data['_view'] = 'module/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a module
     */
    function edit($MODULE_ID)
    {   
        // check if the module exists before trying to edit it
        $data['module'] = $this->Module_model->get_module($MODULE_ID);
        
        if(isset($data['module']['MODULE_ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'MODULE_NAME' => $this->input->post('MODULE_NAME'),
					'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
					'CREATED_DATE' => $this->input->post('CREATED_DATE'),
					'CREATED_BY' => $this->input->post('CREATED_BY'),
                );

                $this->Module_model->update_module($MODULE_ID,$params);            
                redirect('module/index');
            }
            else
            {
                $data['_view'] = 'module/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The module you are trying to edit does not exist.');
    } 

    /*
     * Deleting module
     */
    function remove($MODULE_ID)
    {
        $module = $this->Module_model->get_module($MODULE_ID);

        // check if the module exists before trying to delete it
        if(isset($module['MODULE_ID']))
        {
            $this->Module_model->delete_module($MODULE_ID);
            redirect('module/index');
        }
        else
            show_error('The module you are trying to delete does not exist.');
    }
    
}
