<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Role extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Role_model');
    } 

    /*
     * Listing of roles
     */
    function index()
    {
        $data['roles'] = $this->Role_model->get_all_roles();

        $data['_view'] = 'role/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new role
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'ROLE_NAME' => $this->input->post('ROLE_NAME'),
				'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
            );
            
            $role_id = $this->Role_model->add_role($params);
            redirect('role/index');
        }
        else
        {            
            $data['_view'] = 'role/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a role
     */
    function edit($ROLE_ID)
    {   
        // check if the role exists before trying to edit it
        $data['role'] = $this->Role_model->get_role($ROLE_ID);
        
        if(isset($data['role']['ROLE_ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'ROLE_NAME' => $this->input->post('ROLE_NAME'),
					'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
                );

                $this->Role_model->update_role($ROLE_ID,$params);            
                redirect('role/index');
            }
            else
            {
                $data['_view'] = 'role/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The role you are trying to edit does not exist.');
    } 

    /*
     * Deleting role
     */
    function remove($ROLE_ID)
    {
        $role = $this->Role_model->get_role($ROLE_ID);

        // check if the role exists before trying to delete it
        if(isset($role['ROLE_ID']))
        {
            $this->Role_model->delete_role($ROLE_ID);
            redirect('role/index');
        }
        else
            show_error('The role you are trying to delete does not exist.');
    }
    
}
