<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Userrights_by_user extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Userrights_by_user_model');
        $session_data = (isset($this->session->userdata['EMP_DATA']) && !empty($this->session->userdata['EMP_DATA'])) ? $this->session->userdata['EMP_DATA'] : array();
        if (empty($session_data))
            redirect("login");
    }

    /*
     * Listing of userrights_by_users
     */

    function index() {
        $data['userrights_by_users'] = $this->Userrights_by_user_model->get_all_userrights_by_users();

        $data['_view'] = 'userrights_by_user/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new userrights_by_user
     */

    function add() {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'FORM_ID' => $this->input->post('FORM_ID'),
                'FORM_VIEW' => $this->input->post('FORM_VIEW'),
                'FORM_ADD' => $this->input->post('FORM_ADD'),
                'FORM_EDIT' => $this->input->post('FORM_EDIT'),
                'FORM_DELETE' => $this->input->post('FORM_DELETE'),
                'FORM_REPORT' => $this->input->post('FORM_REPORT'),
                'USER_ID' => $this->input->post('USER_ID'),
                'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
                'CREATED_BY' => $this->input->post('CREATED_BY'),
                'CREATED_DATE' => $this->input->post('CREATED_DATE'),
                'MODIFIED_BY' => $this->input->post('MODIFIED_BY'),
                'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
            );

            $userrights_by_user_id = $this->Userrights_by_user_model->add_userrights_by_user($params);
            redirect('userrights_by_user/index');
        } else {
            $data['_view'] = 'userrights_by_user/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a userrights_by_user
     */

    function edit($UR_ID) {
        // check if the userrights_by_user exists before trying to edit it
        $data['userrights_by_user'] = $this->Userrights_by_user_model->get_userrights_by_user($UR_ID);

        if (isset($data['userrights_by_user']['UR_ID'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'FORM_ID' => $this->input->post('FORM_ID'),
                    'FORM_VIEW' => $this->input->post('FORM_VIEW'),
                    'FORM_ADD' => $this->input->post('FORM_ADD'),
                    'FORM_EDIT' => $this->input->post('FORM_EDIT'),
                    'FORM_DELETE' => $this->input->post('FORM_DELETE'),
                    'FORM_REPORT' => $this->input->post('FORM_REPORT'),
                    'USER_ID' => $this->input->post('USER_ID'),
                    'IS_ACTIVE' => $this->input->post('IS_ACTIVE'),
                    'CREATED_BY' => $this->input->post('CREATED_BY'),
                    'CREATED_DATE' => $this->input->post('CREATED_DATE'),
                    'MODIFIED_BY' => $this->input->post('MODIFIED_BY'),
                    'MODIFIED_DATE' => $this->input->post('MODIFIED_DATE'),
                );

                $this->Userrights_by_user_model->update_userrights_by_user($UR_ID, $params);
                redirect('userrights_by_user/index');
            } else {
                $data['_view'] = 'userrights_by_user/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The userrights_by_user you are trying to edit does not exist.');
    }

    /*
     * Deleting userrights_by_user
     */

    function remove($UR_ID) {
        $userrights_by_user = $this->Userrights_by_user_model->get_userrights_by_user($UR_ID);

        // check if the userrights_by_user exists before trying to delete it
        if (isset($userrights_by_user['UR_ID'])) {
            $this->Userrights_by_user_model->delete_userrights_by_user($UR_ID);
            redirect('userrights_by_user/index');
        } else
            show_error('The userrights_by_user you are trying to delete does not exist.');
    }

}
