<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Administration_setting_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /*
     * Get administration_setting by SETTINGS_ID
     */

    function get_administration_setting($SETTINGS_ID) {
        return $this->db->get_where('administration_settings', array('SETTINGS_ID' => $SETTINGS_ID))->row_array();
    }

    /**
     * Function to get all admin settings
     * 
     * @param type $request
     * @param type $user_data
     * 
     * @return boolean
     */
    function get_all_administration_settings($request, $user_data = array()) {
        try {
            $sql_details = array('user' => $this->db->username, 'pass' => $this->db->password, 'db' => $this->db->database, 'host' => $this->db->hostname);
            $request['searchcolumns'] = array();
            $columns = array(
                array(
                    'db' => 'SETTINGS_ID',
                    'dt' => 'DT_RowId',
                    'formatter' => function( $d, $row ) {
                        return 'row_' . $d;
                    }
                ),
                array('db' => 'SETTINGS_ID',
                    'dt' => 0,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'BRANCH_ID',
                    'dt' => 1,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'LATE_PAYMENT_CHARGES',
                    'dt' => 2,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'SITE_VISIT_CHARGES',
                    'dt' => 3,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'LOD_CHARGES',
                    'dt' => 4,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'OTHER_CHARGES',
                    'dt' => 5,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'GIVEN_DISCOUNT',
                    'dt' => 6,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'STAMPING_CHARGES',
                    'dt' => 7,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'PROCESSING_FEES',
                    'dt' => 8,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'FILING_CHARGES',
                    'dt' => 9,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'CASH_ACCOUNT',
                    'dt' => 10,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'BANK_ACCOUNT',
                    'dt' => 11,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'NEW_LOAN_ACCOUNT_GIVEN',
                    'dt' => 12,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'RECEIVED_CAPITAL',
                    'dt' => 13,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'RECEIVED_INTEREST',
                    'dt' => 14,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'LOANS_TAKEN_INVESTMENT',
                    'dt' => 15,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'PAID_CAPITAL_INVESTMENT',
                    'dt' => 16,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'PAID_INTEREST',
                    'dt' => 17,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'APPLICATION_NO',
                    'dt' => 18,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'PAY_VOUCHER',
                    'dt' => 19,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'PERSONAL_LOAN_NO',
                    'dt' => 20,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'CHEQUE_LOAN_NO',
                    'dt' => 21,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'HIRE_PURCHASE_LOAN_NO',
                    'dt' => 22,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'SECURITY_LOAN_NO',
                    'dt' => 23,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ), array('db' => 'CHEQUE_VS_LOAN',
                    'dt' => 24,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'ALLOW_FUTURE_DATE',
                    'dt' => 25,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ), array('db' => 'CALCULATION_TYPE',
                    'dt' => 26,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ), array('db' => 'ADVANCE_LOAN',
                    'dt' => 27,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ), array('db' => 'STATEMENT',
                    'dt' => 28,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'FLEXIBILITY_OF_INTEREST',
                    'dt' => 29,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'INTEREST_TYPE',
                    'dt' => 30,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
//                array('db' => 'PAYMENT_MODE',
//                    'dt' => 31,
//                    'formatter' => function($d, $row) {
//                        return !empty($d) ? $d : "N/A";
//                    }
//                ),
//                array('db' => 'GOLD_LOAN',
//                    'dt' => 32,
//                    'formatter' => function($d, $row) {
//                        return !empty($d) ? $d : "N/A";
//                    }
//                ),
//                array('db' => 'A',
//                    'dt' => 33,
//                    'formatter' => function($d, $row) {
//                        return !empty($d) ? $d : "N/A";
//                    }
//                ),
//                array('db' => 'B',
//                    'dt' => 34,
//                    'formatter' => function($d, $row) {
//                        return !empty($d) ? $d : "N/A";
//                    }
//                ),
//                array('db' => 'C',
//                    'dt' => 35,
//                    'formatter' => function($d, $row) {
//                        return !empty($d) ? $d : "N/A";
//                    }
//                ),
//                array('db' => 'D',
//                    'dt' => 36,
//                    'formatter' => function($d, $row) {
//                        return !empty($d) ? $d : "N/A";
//                    }
//                ),
//                array('db' => 'E',
//                    'dt' => 37,
//                    'formatter' => function($d, $row) {
//                        return !empty($d) ? $d : "N/A";
//                    }
//                ),
//                array('db' => 'F',
//                    'dt' => 38,
//                    'formatter' => function($d, $row) {
//                        return !empty($d) ? $d : "N/A";
//                    }
//                ),
//                array('db' => 'G',
//                    'dt' => 39,
//                    'formatter' => function($d, $row) {
//                        return !empty($d) ? $d : "N/A";
//                    }
//                ),
//                array('db' => 'H',
//                    'dt' => 40,
//                    'formatter' => function($d, $row) {
//                        return !empty($d) ? $d : "N/A";
//                    }
//                ),
//                array('db' => 'MAX_SMS_PER_WEEK',
//                    'dt' => 41,
//                    'formatter' => function($d, $row) {
//                        return !empty($d) ? $d : "N/A";
//                    }
//                ),
//                array('db' => 'CREATED_DATE',
//                    'dt' => 42,
//                    'formatter' => function($d, $row) {
//                        return !empty($d) ? $d : "N/A";
//                    }
//                ),
//                array('db' => 'CREATED_BY',
//                    'dt' => 43,
//                    'formatter' => function($d, $row) {
//                        return !empty($d) ? $d : "N/A";
//                    }
//                ), array('db' => 'MODIFIED_DATE',
//                    'dt' => 44,
//                    'formatter' => function($d, $row) {
//                        return !empty($d) ? $d : "N/A";
//                    }
//                ),
//                array('db' => 'MODIFIED_BY',
//                    'dt' => 45,
//                    'formatter' => function($d, $row) {
//                        return !empty($d) ? $d : "N/A";
//                    }
//                ),
                array('db' => 'SETTINGS_ID',
                    'dt' => 31,
                    'formatter' => function($d, $row) {
                        $returnString = "";
                        $returnString .= '<a href="' . site_url('administration_setting/edit/' . $d) . '" class="btn btn-info btn-xs"><span class="fa fa-pencil"></span> Edit</a><br>';
                        $returnString .= '<a href="' . site_url('administration_setting/remove/' . $d) . '" class="btn btn-danger btn-xs"><span class="fa fa-trash"></span> Delete</a>';
                        return $returnString;
                    }
                )
            );
            $join = "";
            $where = "";

            $query_columns_array = array("SETTINGS_ID, BRANCH_ID,LATE_PAYMENT_CHARGES, SITE_VISIT_CHARGES, LOD_CHARGES, OTHER_CHARGES, GIVEN_DISCOUNT, STAMPING_CHARGES, PROCESSING_FEES, FILING_CHARGES, CASH_ACCOUNT, BANK_ACCOUNT, NEW_LOAN_ACCOUNT_GIVEN, RECEIVED_CAPITAL, RECEIVED_INTEREST, LOANS_TAKEN_INVESTMENT, PAID_CAPITAL_INVESTMENT, PAID_INTEREST, APPLICATION_NO, PAY_VOUCHER, PERSONAL_LOAN_NO, CHEQUE_LOAN_NO, HIRE_PURCHASE_LOAN_NO, SECURITY_LOAN_NO, CHEQUE_VS_LOAN, ALLOW_FUTURE_DATE, CALCULATION_TYPE, ADVANCE_LOAN, STATEMENT, FLEXIBILITY_OF_INTEREST, INTEREST_TYPE, PAYMENT_MODE, GOLD_LOAN, A, B, C, D, E, F, G, H, MAX_SMS_PER_WEEK, CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_BY");

            $custom_where = array();
            $where .= "";
            $custom_where_string = (count($custom_where) > 0) ? implode(" AND ", array_unique($custom_where)) : "";
            $request['custom_where'] = $custom_where_string;
            $query_columns = implode(",", array_unique($query_columns_array));
            $sql_query = 'SELECT $query_columns from administration_settings' . $join . $where;
            $result = datatable::simple($request, $sql_details, $sql_query, $query_columns, $columns);
            $start = $_REQUEST['start'];
            return $result;
        } catch (Exception $e) {
            log_message("Error", $e->getMessage());
            return false;
        }
    }

    /*
     * function to add new administration_setting
     */

    function add_administration_setting($params) {
        $this->db->insert('administration_settings', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update administration_setting
     */

    function update_administration_setting($SETTINGS_ID, $params) {
        $this->db->where('SETTINGS_ID', $SETTINGS_ID);
        $response = $this->db->update('administration_settings', $params);
        if ($response) {
            return "administration_setting updated successfully";
        } else {
            return "Error occuring while updating administration_setting";
        }
    }

    /*
     * function to delete administration_setting
     */

    function delete_administration_setting($SETTINGS_ID) {
        $response = $this->db->delete('administration_settings', array('SETTINGS_ID' => $SETTINGS_ID));
        if ($response) {
            return "administration_setting deleted successfully";
        } else {
            return "Error occuring while deleting administration_setting";
        }
    }

}
