<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Administration_designation_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get administration_designation by DESIGNATION_ID
     */
    function get_administration_designation($DESIGNATION_ID)
    {
        return $this->db->get_where('administration_designation',array('DESIGNATION_ID'=>$DESIGNATION_ID))->row_array();
    }
    
    /*
     * Get all administration_designation
     */
    function get_all_administration_designation()
    {
        return $this->db->get('administration_designation')->result_array();
    }
    
    /*
     * function to add new administration_designation
     */
    function add_administration_designation($params)
    {
        $this->db->insert('administration_designation',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update administration_designation
     */
    function update_administration_designation($DESIGNATION_ID,$params)
    {
        $this->db->where('DESIGNATION_ID',$DESIGNATION_ID);
        $response = $this->db->update('administration_designation',$params);
        if($response)
        {
            return "administration_designation updated successfully";
        }
        else
        {
            return "Error occuring while updating administration_designation";
        }
    }
    
    /*
     * function to delete administration_designation
     */
    function delete_administration_designation($DESIGNATION_ID)
    {
        $response = $this->db->delete('administration_designation',array('DESIGNATION_ID'=>$DESIGNATION_ID));
        if($response)
        {
            return "administration_designation deleted successfully";
        }
        else
        {
            return "Error occuring while deleting administration_designation";
        }
    }
}
