<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Administration_fundallocation_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get administration_fundallocation by FA_ID
     */
    function get_administration_fundallocation($FA_ID)
    {
        return $this->db->get_where('administration_fundallocation',array('FA_ID'=>$FA_ID))->row_array();
    }
    
    /*
     * Get all administration_fundallocation
     */
    function get_all_administration_fundallocation()
    {
        return $this->db->get('administration_fundallocation')->result_array();
    }
    
    /*
     * function to add new administration_fundallocation
     */
    function add_administration_fundallocation($params)
    {
        $this->db->insert('administration_fundallocation',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update administration_fundallocation
     */
    function update_administration_fundallocation($FA_ID,$params)
    {
        $this->db->where('FA_ID',$FA_ID);
        $response = $this->db->update('administration_fundallocation',$params);
        if($response)
        {
            return "administration_fundallocation updated successfully";
        }
        else
        {
            return "Error occuring while updating administration_fundallocation";
        }
    }
    
    /*
     * function to delete administration_fundallocation
     */
    function delete_administration_fundallocation($FA_ID)
    {
        $response = $this->db->delete('administration_fundallocation',array('FA_ID'=>$FA_ID));
        if($response)
        {
            return "administration_fundallocation deleted successfully";
        }
        else
        {
            return "Error occuring while deleting administration_fundallocation";
        }
    }
}
