<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Administration_employee_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get administration_employee by EMP_ID
     */
    function get_administration_employee($EMP_ID)
    {
        return $this->db->get_where('administration_employees',array('EMP_ID'=>$EMP_ID))->row_array();
    }
    
    /*
     * Get all administration_employees
     */
    function get_all_administration_employees()
    {
        return $this->db->get('administration_employees')->result_array();
    }
    
    /*
     * function to add new administration_employee
     */
    function add_administration_employee($params)
    {
        $this->db->insert('administration_employees',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update administration_employee
     */
    function update_administration_employee($EMP_ID,$params)
    {
        $this->db->where('EMP_ID',$EMP_ID);
        $response = $this->db->update('administration_employees',$params);
        if($response)
        {
            return "administration_employee updated successfully";
        }
        else
        {
            return "Error occuring while updating administration_employee";
        }
    }
    
    /*
     * function to delete administration_employee
     */
    function delete_administration_employee($EMP_ID)
    {
        $response = $this->db->delete('administration_employees',array('EMP_ID'=>$EMP_ID));
        if($response)
        {
            return "administration_employee deleted successfully";
        }
        else
        {
            return "Error occuring while deleting administration_employee";
        }
    }
}
