<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Administration_login_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /*
     * Get administration_login by LOGIN_ID
     */

    function get_administration_login($LOGIN_ID) {
        return $this->db->get_where('administration_logins', array('LOGIN_ID' => $LOGIN_ID))->row_array();
    }

    /**
     * Funciton to get all admin logins
     * 
     * @param type $request
     * @param type $user_data
     * 
     * @return boolean
     */
    function get_all_administration_logins($request, $user_data = array()) {
        try {
            $sql_details = array('user' => $this->db->username, 'pass' => $this->db->password, 'db' => $this->db->database, 'host' => $this->db->hostname);
            $request['searchcolumns'] = array();
            $columns = array(
                array(
                    'db' => 'LOGIN_ID',
                    'dt' => 'DT_RowId',
                    'formatter' => function( $d, $row ) {
                        return 'row_' . $d;
                    }
                ),
                array('db' => 'LOGIN_ID',
                    'dt' => 0,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'EMP_NAME',
                    'dt' => 1,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'LOGIN_USERNAME',
                    'dt' => 2,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'LOGIN_ID',
                    'dt' => 3,
                    'formatter' => function($d, $row) {
                        $returnString = "";
                        $returnString .= '<a href="' . site_url('administration_login/edit/' . $d) . '" class="btn btn-info btn-xs"><span class="fa fa-pencil"></span> Edit</a>&nbsp;&nbsp;';
                        $returnString .= '<a data-href="' . site_url('administration_login/remove') . '" data-table-name="admin_login_table" data-id=' . $d . ' data-desc="You will be perminently deleting this login." data-message= "Are you sure to delete?" class="btn btn-danger btn-xs delete-row"><span class="fa fa-trash"></span> Delete</a>';
                        return $returnString;
                    }
                )
            );
            $join = "";
            $join .= " JOIN administration_employees ae ON ae.EMP_ID = al.EMP_ID AND ae.IS_ACTIVE = 1 AND ae.CREATED_BY = " . $this->session->userdata["EMP_DATA"]['EMP_ID'];
            $where = "";

            $query_columns_array = array("LOGIN_ID, LOGIN_USERNAME, LOGIN_PASSWORD, EMP_NAME");

            $custom_where = array();
            $where .= " WHERE al.IS_ACTIVE = 1 AND al.CREATED_BY = " . $this->session->userdata["EMP_DATA"]['EMP_ID'];
            $custom_where_string = (count($custom_where) > 0) ? implode(" AND ", array_unique($custom_where)) : "";
            $request['custom_where'] = $custom_where_string;
            $query_columns = implode(",", array_unique($query_columns_array));
            $sql_query = 'SELECT $query_columns from administration_logins al' . $join . $where;
            $result = datatable::simple($request, $sql_details, $sql_query, $query_columns, $columns);
            $start = $_REQUEST['start'];
            return $result;
        } catch (Exception $e) {
            log_message("Error", $e->getMessage());
            return false;
        }
    }

    /*
     * function to add new administration_login
     */

    function add_administration_login($params) {
        $this->db->insert('administration_logins', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update administration_login
     */

    function update_administration_login($LOGIN_ID, $params) {
        $this->db->where('LOGIN_ID', $LOGIN_ID);
        return $this->db->update('administration_logins', $params);
    }

    /*
     * function to delete administration_login
     */

    function delete_administration_login($LOGIN_ID) {
        return $this->db->where(array('LOGIN_ID' => $LOGIN_ID))->update('administration_logins', array("IS_ACTIVE" => 0));
    }

}
