<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Administration_comp_profile_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get administration_comp_profile by BRANCH_ID
     */
    function get_administration_comp_profile($BRANCH_ID)
    {
        return $this->db->get_where('administration_comp_profile',array('BRANCH_ID'=>$BRANCH_ID))->row_array();
    }
    
    /*
     * Get all administration_comp_profile
     */
    function get_all_administration_comp_profile()
    {
        return $this->db->get('administration_comp_profile')->result_array();
    }
    
    /*
     * function to add new administration_comp_profile
     */
    function add_administration_comp_profile($params)
    {
        $this->db->insert('administration_comp_profile',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update administration_comp_profile
     */
    function update_administration_comp_profile($BRANCH_ID,$params)
    {
        $this->db->where('BRANCH_ID',$BRANCH_ID);
        $response = $this->db->update('administration_comp_profile',$params);
        if($response)
        {
            return "administration_comp_profile updated successfully";
        }
        else
        {
            return "Error occuring while updating administration_comp_profile";
        }
    }
    
    /*
     * function to delete administration_comp_profile
     */
    function delete_administration_comp_profile($BRANCH_ID)
    {
        $response = $this->db->delete('administration_comp_profile',array('BRANCH_ID'=>$BRANCH_ID));
        if($response)
        {
            return "administration_comp_profile deleted successfully";
        }
        else
        {
            return "Error occuring while deleting administration_comp_profile";
        }
    }
}
