<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Administration_setting_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get administration_setting by SETTINGS_ID
     */
    function get_administration_setting($SETTINGS_ID)
    {
        return $this->db->get_where('administration_settings',array('SETTINGS_ID'=>$SETTINGS_ID))->row_array();
    }
    
    /*
     * Get all administration_settings
     */
    function get_all_administration_settings()
    {
        return $this->db->get('administration_settings')->result_array();
    }
    
    /*
     * function to add new administration_setting
     */
    function add_administration_setting($params)
    {
        $this->db->insert('administration_settings',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update administration_setting
     */
    function update_administration_setting($SETTINGS_ID,$params)
    {
        $this->db->where('SETTINGS_ID',$SETTINGS_ID);
        $response = $this->db->update('administration_settings',$params);
        if($response)
        {
            return "administration_setting updated successfully";
        }
        else
        {
            return "Error occuring while updating administration_setting";
        }
    }
    
    /*
     * function to delete administration_setting
     */
    function delete_administration_setting($SETTINGS_ID)
    {
        $response = $this->db->delete('administration_settings',array('SETTINGS_ID'=>$SETTINGS_ID));
        if($response)
        {
            return "administration_setting deleted successfully";
        }
        else
        {
            return "Error occuring while deleting administration_setting";
        }
    }
}
