<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Administration_employee_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /*
     * Get administration_employee by EMP_ID
     */

    function get_administration_employee($EMP_ID) {
        return $this->db->get_where('administration_employees', array('EMP_ID' => $EMP_ID))->row_array();
    }

    /**
     * Get all administration_employees
     * 
     * @param array $request
     * @param array $user_data
     * 
     * @return array result
     */
    function get_all_administration_employees($request, $user_data = array()) {
        try {
            $sql_details = array('user' => $this->db->username, 'pass' => $this->db->password, 'db' => $this->db->database, 'host' => $this->db->hostname);
            $request['searchcolumns'] = array();
            $columns = array(
                array(
                    'db' => 'EMP_ID',
                    'dt' => 'DT_RowId',
                    'formatter' => function( $d, $row ) {
                        return 'row_' . $d;
                    }
                ),
                array('db' => 'EMP_ID',
                    'dt' => 0,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'EMP_NAME',
                    'dt' => 1,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'CLIENT_ID',
                    'dt' => 2,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'IS_ACTIVE',
                    'dt' => 3,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'CREATED_DATE',
                    'dt' => 4,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'CREATED_BY',
                    'dt' => 5,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ), array('db' => 'MODIFIED_DATE',
                    'dt' => 6,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'MODIFIED_BY',
                    'dt' => 7,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'IC_NO',
                    'dt' => 8,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'STAFF_NO',
                    'dt' => 9,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'ADDRESS',
                    'dt' => 10,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'MOBILE_NO',
                    'dt' => 11,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'PHONE_NO',
                    'dt' => 12,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'EMAIL_ID',
                    'dt' => 13,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'GENDER',
                    'dt' => 14,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'DESIGNATION_ID',
                    'dt' => 15,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'ACTIVE_STATUS',
                    'dt' => 16,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'BASIC_SALARY',
                    'dt' => 17,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'LANGUAGE',
                    'dt' => 18,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'EMPLOYEE_PIC_PATH',
                    'dt' => 19,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'VIEW_OTHER_BRANCH_DETAILS',
                    'dt' => 20,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'MULTIPLE_LOGINS',
                    'dt' => 21,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'ROLE_ID',
                    'dt' => 22,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'EMP_ID',
                    'dt' => 23,
                    'formatter' => function($d, $row) {
                        $returnString = "";
                        $returnString .= '<a href="' . site_url('administration_employee/edit/' . $d) . '" class="btn btn-info btn-xs"><span class="fa fa-pencil"></span> Edit</a><br>';
                        $returnString .= '<a href="' . site_url('administration_employee/remove/' . $d) . '" class="btn btn-danger btn-xs"><span class="fa fa-trash"></span> Delete</a>';
                        return $returnString;
                    }
                )
            );
            $join = "";
            $where = "";

            $query_columns_array = array("EMP_ID, EMP_NAME, CLIENT_ID, IS_ACTIVE, CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_BY, IC_NO, STAFF_NO, ADDRESS, MOBILE_NO, PHONE_NO, EMAIL_ID, GENDER, DESIGNATION_ID, ACTIVE_STATUS, BASIC_SALARY, LANGUAGE, EMPLOYEE_PIC_PATH, VIEW_OTHER_BRANCH_DETAILS, MULTIPLE_LOGINS, ROLE_ID");

            $custom_where = array();
            $where .= "";
            $custom_where_string = (count($custom_where) > 0) ? implode(" AND ", array_unique($custom_where)) : "";
            $request['custom_where'] = $custom_where_string;
            $query_columns = implode(",", array_unique($query_columns_array));
            $sql_query = 'SELECT $query_columns from administration_employees' . $join . $where;
            $result = datatable::simple($request, $sql_details, $sql_query, $query_columns, $columns);
            $start = $_REQUEST['start'];
            return $result;
        } catch (Exception $e) {
            log_message("Error", $e->getMessage());
            return false;
        }
    }

    /*
     * function to add new administration_employee
     */

    function add_administration_employee($params) {
        $this->db->insert('administration_employees', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update administration_employee
     */

    function update_administration_employee($EMP_ID, $params) {
        $this->db->where('EMP_ID', $EMP_ID);
        $response = $this->db->update('administration_employees', $params);
        if ($response) {
            return "administration_employee updated successfully";
        } else {
            return "Error occuring while updating administration_employee";
        }
    }

    /*
     * function to delete administration_employee
     */

    function delete_administration_employee($EMP_ID) {
        $response = $this->db->delete('administration_employees', array('EMP_ID' => $EMP_ID));
        if ($response) {
            return "administration_employee deleted successfully";
        } else {
            return "Error occuring while deleting administration_employee";
        }
    }

}
