<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Administration_fundallocation_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /*
     * Get administration_fundallocation by FA_ID
     */

    function get_administration_fundallocation($FA_ID) {
        return $this->db->get_where('administration_fundallocation', array('FA_ID' => $FA_ID))->row_array();
    }

    /**
     * Get all administration_fundallocation
     * 
     * @param type $request
     * @param type $user_data
     * 
     * @return type
     */
    function get_all_administration_fundallocation($request, $user_data = array()) {
        try {
            $sql_details = array('user' => $this->db->username, 'pass' => $this->db->password, 'db' => $this->db->database, 'host' => $this->db->hostname);
            $request['searchcolumns'] = array();
            $columns = array(
                array(
                    'db' => 'FA_ID',
                    'dt' => 'DT_RowId',
                    'formatter' => function( $d, $row ) {
                        return 'row_' . $d;
                    }
                ),
                array('db' => 'FA_ID',
                    'dt' => 0,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'FA_DATE',
                    'dt' => 1,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'EMP_NAME',
                    'dt' => 2,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'Amount',
                    'dt' => 3,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'FA_ID',
                    'dt' => 4,
                    'formatter' => function($d, $row) {
                        $returnString = "";
                        $returnString .= '<a href="' . site_url('administration_fundallocation/edit/' . $d) . '" class="btn btn-info btn-xs"><span class="fa fa-pencil"></span> Edit</a>&nbsp;&nbsp;';
                        $returnString .= '<a data-href="' . site_url('administration_fundallocation/remove') . '" data-table-name="admin_fund_table" data-id=' . $d . ' data-desc="You will be perminently deleting this client." data-message= "Are you sure to delete?" class="btn btn-danger btn-xs delete-row"><span class="fa fa-trash"></span> Delete</a>';
                        return $returnString;
                    }
                )
            );
            $join = "";
            $join .= " JOIN administration_employees ae ON ae.EMP_ID = af.EMP_ID AND ae.IS_ACTIVE = 1 AND ae.CREATED_BY = " . $this->session->userdata["EMP_DATA"]['EMP_ID'];
            $where = "";

            $query_columns_array = array("FA_ID, FA_DATE, Amount, EMP_NAME");

            $custom_where = array();
            $where .= " WHERE af.IS_ACTIVE = 1 AND af.CREATED_BY = " . $this->session->userdata["EMP_DATA"]['EMP_ID'];
            $custom_where_string = (count($custom_where) > 0) ? implode(" AND ", array_unique($custom_where)) : "";
            $request['custom_where'] = $custom_where_string;
            $query_columns = implode(",", array_unique($query_columns_array));
            $sql_query = 'SELECT $query_columns from administration_fundallocation af' . $join . $where;
            $result = datatable::simple($request, $sql_details, $sql_query, $query_columns, $columns);
            $start = $_REQUEST['start'];
            return $result;
        } catch (Exception $e) {
            log_message("Error", $e->getMessage());
            return false;
        }
    }

    /*
     * function to add new administration_fundallocation
     */

    function add_administration_fundallocation($params) {
        $this->db->insert('administration_fundallocation', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update administration_fundallocation
     */

    function update_administration_fundallocation($FA_ID, $params) {
        $this->db->where('FA_ID', $FA_ID);
        return $this->db->update('administration_fundallocation', $params);
    }

    /*
     * function to delete administration_fundallocation
     */

    function delete_administration_fundallocation($FA_ID) {
        return $this->db->where(array("FA_ID" => $FA_ID))->update('administration_fundallocation', array('IS_ACTIVE' => 0));
    }

}
