<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Administration_emp_branch_info_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get administration_emp_branch_info by ID
     */
    function get_administration_emp_branch_info($ID)
    {
        return $this->db->get_where('administration_emp_branch_info',array('ID'=>$ID))->row_array();
    }
    
    /*
     * Get all administration_emp_branch_info
     */
    function get_all_administration_emp_branch_info()
    {
        return $this->db->get('administration_emp_branch_info')->result_array();
    }
    
    /*
     * function to add new administration_emp_branch_info
     */
    function add_administration_emp_branch_info($params)
    {
        $this->db->insert('administration_emp_branch_info',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update administration_emp_branch_info
     */
    function update_administration_emp_branch_info($ID,$params)
    {
        $this->db->where('ID',$ID);
        $response = $this->db->update('administration_emp_branch_info',$params);
        if($response)
        {
            return "administration_emp_branch_info updated successfully";
        }
        else
        {
            return "Error occuring while updating administration_emp_branch_info";
        }
    }
    
    /*
     * function to delete administration_emp_branch_info
     */
    function delete_administration_emp_branch_info($ID)
    {
        $response = $this->db->delete('administration_emp_branch_info',array('ID'=>$ID));
        if($response)
        {
            return "administration_emp_branch_info deleted successfully";
        }
        else
        {
            return "Error occuring while deleting administration_emp_branch_info";
        }
    }
}
