<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Client_info_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /**
     * Function to get all clients data
     * 
     * @param array $request
     * @param array $user_data
     * 
     * @return array $result
     */
    function getAllClientsData($request, $user_data = array()) {
        try {
            $sql_details = array('user' => $this->db->username, 'pass' => $this->db->password, 'db' => $this->db->database, 'host' => $this->db->hostname);
            $request['searchcolumns'] = array();
            $columns = array(
                array(
                    'db' => 'CLIENT_ID',
                    'dt' => 'DT_RowId',
                    'formatter' => function( $d, $row ) {
                        return 'row_' . $d;
                    }
                ),
                array('db' => 'CLIENT_ID',
                    'dt' => 0,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'CLIENT_CODE',
                    'dt' => 1,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'CLIENT_NAME',
                    'dt' => 2,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'CLIENT_ID',
                    'dt' => 3,
                    'formatter' => function($d, $row) {
                        $returnString = "";
                        $returnString .= '<a href="' . site_url('client_info/edit/' . $row['CLIENT_ID']) . '" class="btn btn-info btn-xs"><span class="fa fa-pencil"></span> Edit</a>&nbsp;&nbsp;';
                        $returnString .= '<a data-href="' . site_url('client_info/remove') . '" data-table-name="client_info_add" data-id=' . $row["CLIENT_ID"] . ' data-desc="You will be perminently deleting this client." data-message= "Are you sure to delete?" class="btn btn-danger btn-xs delete-row"><span class="fa fa-trash"></span> Delete</a>';
                        return $returnString;
                    }
                )
            );
            $join = "";
            $where = "";

            $query_columns_array = array("CLIENT_ID", "CLIENT_CODE", "CLIENT_NAME");

            $custom_where = array();
            $where .= " WHERE IS_ACTIVE = 1";
            $custom_where_string = (count($custom_where) > 0) ? implode(" AND ", array_unique($custom_where)) : "";
            $request['custom_where'] = $custom_where_string;
            $query_columns = implode(",", array_unique($query_columns_array));
            $sql_query = 'SELECT $query_columns from client_info' . $join . $where;
            $result = datatable::simple($request, $sql_details, $sql_query, $query_columns, $columns);
            $start = $_REQUEST['start'];
            return $result;
        } catch (Exception $e) {
            log_message("ERROR", "Something went wrong with clients table - Message : " . $e->getMessage());
            return false;
        }
    }

    /*
     * Get client_info by CLIENT_ID
     */

    function get_client_info($CLIENT_ID) {
        return $this->db->get_where('client_info', array('CLIENT_ID' => $CLIENT_ID))->row_array();
    }

    /*
     * Get all client_info
     */

    function get_all_client_info() {
        return $this->db->where(array("IS_ACTIVE" => 1))->get('client_info')->result_array();
    }

    /*
     * function to add new client_info
     */

    function add_client_info($params) {
        $this->db->insert('client_info', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update client_info
     */

    function update_client_info($CLIENT_ID, $params) {
        $this->db->where('CLIENT_ID', $CLIENT_ID);
        $response = $this->db->update('client_info', $params);
        if ($response) {
            return "client_info updated successfully";
        } else {
            return "Error occuring while updating client_info";
        }
    }

    /*
     * function to delete client_info
     */

    function delete_client_info($CLIENT_ID) {
        return $this->db->where(array('CLIENT_ID' => $CLIENT_ID))->update('client_info', array('IS_ACTIVE' => 0));
    }

}
