<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Customer_doc_checklist_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get customer_doc_checklist by CHECKLIST_ID
     */
    function get_customer_doc_checklist($CHECKLIST_ID)
    {
        return $this->db->get_where('customer_doc_checklist',array('CHECKLIST_ID'=>$CHECKLIST_ID))->row_array();
    }
    
    /*
     * Get all customer_doc_checklist
     */
    function get_all_customer_doc_checklist()
    {
        return $this->db->get('customer_doc_checklist')->result_array();
    }
    
    /*
     * function to add new customer_doc_checklist
     */
    function add_customer_doc_checklist($params)
    {
        $this->db->insert('customer_doc_checklist',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update customer_doc_checklist
     */
    function update_customer_doc_checklist($CHECKLIST_ID,$params)
    {
        $this->db->where('CHECKLIST_ID',$CHECKLIST_ID);
        $response = $this->db->update('customer_doc_checklist',$params);
        if($response)
        {
            return "customer_doc_checklist updated successfully";
        }
        else
        {
            return "Error occuring while updating customer_doc_checklist";
        }
    }
    
    /*
     * function to delete customer_doc_checklist
     */
    function delete_customer_doc_checklist($CHECKLIST_ID)
    {
        $response = $this->db->delete('customer_doc_checklist',array('CHECKLIST_ID'=>$CHECKLIST_ID));
        if($response)
        {
            return "customer_doc_checklist deleted successfully";
        }
        else
        {
            return "Error occuring while deleting customer_doc_checklist";
        }
    }
}
