<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Customer_reference_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get customer_reference by REFERENCE_ID
     */
    function get_customer_reference($REFERENCE_ID)
    {
        return $this->db->get_where('customer_reference',array('REFERENCE_ID'=>$REFERENCE_ID))->row_array();
    }
    
    /*
     * Get all customer_reference
     */
    function get_all_customer_reference()
    {
        return $this->db->get('customer_reference')->result_array();
    }
    
    /*
     * function to add new customer_reference
     */
    function add_customer_reference($params)
    {
        $this->db->insert('customer_reference',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update customer_reference
     */
    function update_customer_reference($REFERENCE_ID,$params)
    {
        $this->db->where('REFERENCE_ID',$REFERENCE_ID);
        $response = $this->db->update('customer_reference',$params);
        if($response)
        {
            return "customer_reference updated successfully";
        }
        else
        {
            return "Error occuring while updating customer_reference";
        }
    }
    
    /*
     * function to delete customer_reference
     */
    function delete_customer_reference($REFERENCE_ID)
    {
        $response = $this->db->delete('customer_reference',array('REFERENCE_ID'=>$REFERENCE_ID));
        if($response)
        {
            return "customer_reference deleted successfully";
        }
        else
        {
            return "Error occuring while deleting customer_reference";
        }
    }
}
