<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Customer_detail_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /**
     * Function to get all customer detail data 
     * 
     * @param array $request
     * @param array $user_data
     * 
     * @return array result
     */
    function get_all_customer_details_data($request, $user_data = array()) {
        try {
            $sql_details = array('user' => $this->db->username, 'pass' => $this->db->password, 'db' => $this->db->database, 'host' => $this->db->hostname);
            $request['searchcolumns'] = array();

            $columns = array(
                array(
                    'db' => 'CUSTOMER_ID',
                    'dt' => 'DT_RowId',
                    'formatter' => function( $d, $row ) {
                        return 'row_' . $d;
                    }
                ),
                array('db' => 'CUSTOMER_ID',
                    'dt' => 0,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'CUSTOMER_NAME',
                    'dt' => 1,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'CUSTOMER_IDNO',
                    'dt' => 2,
                    'formatter' => function($d, $row) {
                        return $d;
                    }
                ),
                array('db' => 'EMAIL_ID',
                    'dt' => 3,
                    'formatter' => function($d, $row) {
                        return $d;
                    }
                ),
                array(
                    'db' => 'CUSTOMER_ID',
                    'dt' => 4,
                    'formatter' => function($d, $row) {
                        $returnString = "";
                        $returnString .= '<a href="' . site_url('customer_detail/add/' . $row['CUSTOMER_ID']) . '" class="btn btn-info btn-xs"><span class="fa fa-pencil"></span> Edit</a>&nbsp;&nbsp;';
                        $returnString .= '<a data-href="' . site_url('customer_detail/remove/') . '" data-table-name="cust_profile_table" data-id=' . $row["CUSTOMER_ID"] . ' data-desc="You will be perminently deleting this customer." data-message= "Are you sure to delete?" class="btn btn-danger btn-xs delete-row"><span class="fa fa-trash"></span> Delete</a>';
                        return $returnString;
                    }
                )
            );

            $join = "";
            $where = "";

            $query_columns_array = array("CUSTOMER_ID", "CUSTOMER_NAME", "CUSTOMER_IDNO", "EMAIL_ID");

            $custom_where = array();
            $where .= " WHERE IS_ACTIVE = 1 AND CREATED_BY = " . $this->session->userdata["EMP_DATA"]['EMP_ID'];
            $custom_where_string = (count($custom_where) > 0) ? implode(" AND ", array_unique($custom_where)) : "";
            $request['custom_where'] = $custom_where_string;
            $query_columns = implode(",", array_unique($query_columns_array));
            $sql_query = 'SELECT $query_columns from customer_details cd' . $join . $where;
            $result = datatable::simple($request, $sql_details, $sql_query, $query_columns, $columns);
            $start = $_REQUEST['start'];
            foreach ($result['data'] as &$res) {
                $start++;
                $res[0] = $start;
            }
            return $result;
        } catch (Exception $e) {
            log_message("Error : ", $this->db->_error_message());
            return fasle;
        }
    }

    /*
     * Get customer_detail by CUSTOMER_ID
     */

    function get_customer_detail($CUSTOMER_ID) {
        return $this->db->get_where('customer_details', array('CUSTOMER_ID' => $CUSTOMER_ID))->row_array();
    }

    /*
     * Get all customer_details
     */

    function get_all_customer_details() {
        return $this->db->get('customer_details')->result_array();
    }

    /*
     * function to add new customer_detail
     */

    function add_customer_detail($params) {
        if (isset($params['id']) && $params['id'] != "" && $params['id'] != 0) {
            $update_data = $params;
            unset($update_data['id']);
            $this->db->where(array("CUSTOMER_ID" => $params['id']))->update('customer_details', $update_data);
        } else
            $this->db->insert('customer_details', $params);
        return true;
    }

    /*
     * function to update customer_detail
     */

    function update_customer_detail($CUSTOMER_ID, $params) {
        $this->db->where('CUSTOMER_ID', $CUSTOMER_ID);
        $response = $this->db->update('customer_details', $params);
        if ($response) {
            return "customer_detail updated successfully";
        } else {
            return "Error occuring while updating customer_detail";
        }
    }

    /*
     * function to delete customer_detail
     */

    function delete_customer_detail($CUSTOMER_ID) {
        $response = $this->db->delete('customer_details', array('CUSTOMER_ID' => $CUSTOMER_ID));
        if ($response) {
            return "customer_detail deleted successfully";
        } else {
            return "Error occuring while deleting customer_detail";
        }
    }

}
