<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Customer_addres_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get customer_addres by CONTACT_ID
     */
    function get_customer_addres($CONTACT_ID)
    {
        return $this->db->get_where('customer_address',array('CONTACT_ID'=>$CONTACT_ID))->row_array();
    }
    
    /*
     * Get all customer_address
     */
    function get_all_customer_address()
    {
        return $this->db->get('customer_address')->result_array();
    }
    
    /*
     * function to add new customer_addres
     */
    function add_customer_addres($params)
    {
        $this->db->insert('customer_address',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update customer_addres
     */
    function update_customer_addres($CONTACT_ID,$params)
    {
        $this->db->where('CONTACT_ID',$CONTACT_ID);
        $response = $this->db->update('customer_address',$params);
        if($response)
        {
            return "customer_addres updated successfully";
        }
        else
        {
            return "Error occuring while updating customer_addres";
        }
    }
    
    /*
     * function to delete customer_addres
     */
    function delete_customer_addres($CONTACT_ID)
    {
        $response = $this->db->delete('customer_address',array('CONTACT_ID'=>$CONTACT_ID));
        if($response)
        {
            return "customer_addres deleted successfully";
        }
        else
        {
            return "Error occuring while deleting customer_addres";
        }
    }
}
