<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Masters_loan_pay_term_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /**
     * Function to get all masters document data
     * 
     * @param type $request
     * @param type $user_data
     * 
     * @return type
     */
    function getAllMastersLoanPayTermsData($request, $user_data) {
        try {
            $sql_details = array('user' => $this->db->username, 'pass' => $this->db->password, 'db' => $this->db->database, 'host' => $this->db->hostname);
            $request['searchcolumns'] = array();

            $columns = array(
                array(
                    'db' => 'LOANTERM_ID',
                    'dt' => 'DT_RowId',
                    'formatter' => function( $d, $row ) {
                        return 'row_' . $d;
                    }
                ),
                array('db' => 'LOANTERM_ID',
                    'dt' => 0,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'LOANTERM_PAYTERM',
                    'dt' => 1,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'LOANTERM_PAYTYPE',
                    'dt' => 2,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'LOANTERM_NOOFTERMS',
                    'dt' => 3,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'LOANTERM_ID',
                    'dt' => 4,
                    'formatter' => function($d, $row) {
                        $returnString = "";
                        $returnString .= '<a href="' . site_url('masters_loan_pay_term/edit/' . $row['LOANTERM_ID']) . '" class="btn btn-info btn-xs"><span class="fa fa-pencil"></span> Edit</a><br>';
                        $returnString .= '<a href="' . site_url('masters_loan_pay_term/remove/' . $row['LOANTERM_ID']) . '" class="btn btn-danger btn-xs"><span class="fa fa-trash"></span> Delete</a>';
                        return $returnString;
                    }
                )
            );

            $join = "";
            $where = "";

            $query_columns_array = array("LOANTERM_ID, LOANTERM_PAYTERM, LOANTERM_PAYTYPE, LOANTERM_NOOFTERMS");

            $custom_where = array();
            $where .= " WHERE CREATED_BY = " . $_SESSION['EMP_DATA']['LOGIN_ID'] . " AND   IS_ACTIVE = 1";
            $custom_where_string = (count($custom_where) > 0) ? implode(" AND ", array_unique($custom_where)) : "";
            $request['custom_where'] = $custom_where_string;
            $query_columns = implode(",", array_unique($query_columns_array));
            $sql_query = 'SELECT $query_columns from masters_loan_pay_terms' . $join . $where;
            $result = datatable::simple($request, $sql_details, $sql_query, $query_columns, $columns);
            $start = $_REQUEST['start'];
            return $result;
        } catch (Exception $e) {
            log_message("Error : ", $this->db->_error_message());
            return fasle;
        }
    }

    /*
     * Get masters_loan_pay_term by LOANTERM_ID
     */

    function get_masters_loan_pay_term($LOANTERM_ID) {
        return $this->db->get_where('masters_loan_pay_terms', array('LOANTERM_ID' => $LOANTERM_ID))->row_array();
    }

    /*
     * Get all masters_loan_pay_terms
     */

    function get_all_masters_loan_pay_terms() {
        return $this->db->get('masters_loan_pay_terms')->result_array();
    }

    /*
     * function to add new masters_loan_pay_term
     */

    function add_masters_loan_pay_term($params) {
        $this->db->insert('masters_loan_pay_terms', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update masters_loan_pay_term
     */

    function update_masters_loan_pay_term($LOANTERM_ID, $params) {
        $this->db->where('LOANTERM_ID', $LOANTERM_ID);
        $response = $this->db->update('masters_loan_pay_terms', $params);
        if ($response) {
            return "masters_loan_pay_term updated successfully";
        } else {
            return "Error occuring while updating masters_loan_pay_term";
        }
    }

    /*
     * function to delete masters_loan_pay_term
     */

    function delete_masters_loan_pay_term($LOANTERM_ID) {
        $response = $this->db->delete('masters_loan_pay_terms', array('LOANTERM_ID' => $LOANTERM_ID));
        if ($response) {
            return "masters_loan_pay_term deleted successfully";
        } else {
            return "Error occuring while deleting masters_loan_pay_term";
        }
    }

}
