<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Masters_daily_gold_price_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get masters_daily_gold_price by GOLD_PRICE_ID
     */
    function get_masters_daily_gold_price($GOLD_PRICE_ID)
    {
        return $this->db->get_where('masters_daily_gold_price',array('GOLD_PRICE_ID'=>$GOLD_PRICE_ID))->row_array();
    }
    
    /*
     * Get all masters_daily_gold_price
     */
    function get_all_masters_daily_gold_price()
    {
        return $this->db->get('masters_daily_gold_price')->result_array();
    }
    
    /*
     * function to add new masters_daily_gold_price
     */
    function add_masters_daily_gold_price($params)
    {
        $this->db->insert('masters_daily_gold_price',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update masters_daily_gold_price
     */
    function update_masters_daily_gold_price($GOLD_PRICE_ID,$params)
    {
        $this->db->where('GOLD_PRICE_ID',$GOLD_PRICE_ID);
        $response = $this->db->update('masters_daily_gold_price',$params);
        if($response)
        {
            return "masters_daily_gold_price updated successfully";
        }
        else
        {
            return "Error occuring while updating masters_daily_gold_price";
        }
    }
    
    /*
     * function to delete masters_daily_gold_price
     */
    function delete_masters_daily_gold_price($GOLD_PRICE_ID)
    {
        $response = $this->db->delete('masters_daily_gold_price',array('GOLD_PRICE_ID'=>$GOLD_PRICE_ID));
        if($response)
        {
            return "masters_daily_gold_price deleted successfully";
        }
        else
        {
            return "Error occuring while deleting masters_daily_gold_price";
        }
    }
}
