<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Masters_jobsector_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get masters_jobsector by JOBSECTOR_ID
     */
    function get_masters_jobsector($JOBSECTOR_ID)
    {
        return $this->db->get_where('masters_jobsector',array('JOBSECTOR_ID'=>$JOBSECTOR_ID))->row_array();
    }
    
    /*
     * Get all masters_jobsector
     */
    function get_all_masters_jobsector()
    {
        return $this->db->get('masters_jobsector')->result_array();
    }
    
    /*
     * function to add new masters_jobsector
     */
    function add_masters_jobsector($params)
    {
        $this->db->insert('masters_jobsector',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update masters_jobsector
     */
    function update_masters_jobsector($JOBSECTOR_ID,$params)
    {
        $this->db->where('JOBSECTOR_ID',$JOBSECTOR_ID);
        $response = $this->db->update('masters_jobsector',$params);
        if($response)
        {
            return "masters_jobsector updated successfully";
        }
        else
        {
            return "Error occuring while updating masters_jobsector";
        }
    }
    
    /*
     * function to delete masters_jobsector
     */
    function delete_masters_jobsector($JOBSECTOR_ID)
    {
        $response = $this->db->delete('masters_jobsector',array('JOBSECTOR_ID'=>$JOBSECTOR_ID));
        if($response)
        {
            return "masters_jobsector deleted successfully";
        }
        else
        {
            return "Error occuring while deleting masters_jobsector";
        }
    }
}
