<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Masters_housestatu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get masters_housestatu by HOUSESTATUS_ID
     */
    function get_masters_housestatu($HOUSESTATUS_ID)
    {
        return $this->db->get_where('masters_housestatus',array('HOUSESTATUS_ID'=>$HOUSESTATUS_ID))->row_array();
    }
    
    /*
     * Get all masters_housestatus
     */
    function get_all_masters_housestatus()
    {
        return $this->db->get('masters_housestatus')->result_array();
    }
    
    /*
     * function to add new masters_housestatu
     */
    function add_masters_housestatu($params)
    {
        $this->db->insert('masters_housestatus',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update masters_housestatu
     */
    function update_masters_housestatu($HOUSESTATUS_ID,$params)
    {
        $this->db->where('HOUSESTATUS_ID',$HOUSESTATUS_ID);
        $response = $this->db->update('masters_housestatus',$params);
        if($response)
        {
            return "masters_housestatu updated successfully";
        }
        else
        {
            return "Error occuring while updating masters_housestatu";
        }
    }
    
    /*
     * function to delete masters_housestatu
     */
    function delete_masters_housestatu($HOUSESTATUS_ID)
    {
        $response = $this->db->delete('masters_housestatus',array('HOUSESTATUS_ID'=>$HOUSESTATUS_ID));
        if($response)
        {
            return "masters_housestatu deleted successfully";
        }
        else
        {
            return "Error occuring while deleting masters_housestatu";
        }
    }
}
