<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Masters_orgtype_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /**
     * Function to get all masters document data
     * 
     * @param type $request
     * @param type $user_data
     * 
     * @return type
     */
    function getAllMastersOrgtypeData($request, $user_data) {
        try {
            $sql_details = array('user' => $this->db->username, 'pass' => $this->db->password, 'db' => $this->db->database, 'host' => $this->db->hostname);
            $request['searchcolumns'] = array();

            $columns = array(
                array(
                    'db' => 'ORGTYPE_ID',
                    'dt' => 'DT_RowId',
                    'formatter' => function( $d, $row ) {
                        return 'row_' . $d;
                    }
                ),
                array('db' => 'ORGTYPE_ID',
                    'dt' => 0,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'ORGTYPE_NAME',
                    'dt' => 1,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'ORGTYPE_ID',
                    'dt' => 2,
                    'formatter' => function($d, $row) {
                        $returnString = "";
                        $returnString .= '<a href="' . site_url('masters_orgtype/edit/' . $row['ORGTYPE_ID']) . '" class="btn btn-info btn-xs"><span class="fa fa-pencil"></span> Edit</a><br>';
                        $returnString .= '<a href="' . site_url('masters_orgtype/remove/' . $row['ORGTYPE_ID']) . '" class="btn btn-danger btn-xs"><span class="fa fa-trash"></span> Delete</a>';
                        return $returnString;
                    }
                )
            );

            $join = "";
            $where = "";

            $query_columns_array = array("ORGTYPE_ID, ORGTYPE_NAME");

            $custom_where = array();
            $where .= " WHERE CREATED_BY = " . $_SESSION['EMP_DATA']['LOGIN_ID'] . " AND   IS_ACTIVE = 1";
            $custom_where_string = (count($custom_where) > 0) ? implode(" AND ", array_unique($custom_where)) : "";
            $request['custom_where'] = $custom_where_string;
            $query_columns = implode(",", array_unique($query_columns_array));
            $sql_query = 'SELECT $query_columns from masters_orgtype' . $join . $where;
            $result = datatable::simple($request, $sql_details, $sql_query, $query_columns, $columns);
            $start = $_REQUEST['start'];
            return $result;
        } catch (Exception $e) {
            log_message("Error : ", $this->db->_error_message());
            return fasle;
        }
    }

    /*
     * Get masters_orgtype by ORGTYPE_ID
     */

    function get_masters_orgtype($ORGTYPE_ID) {
        return $this->db->get_where('masters_orgtype', array('ORGTYPE_ID' => $ORGTYPE_ID))->row_array();
    }

    /*
     * Get all masters_orgtype
     */

    function get_all_masters_orgtype() {
        return $this->db->get('masters_orgtype')->result_array();
    }

    /*
     * function to add new masters_orgtype
     */

    function add_masters_orgtype($params) {
        $this->db->insert('masters_orgtype', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update masters_orgtype
     */

    function update_masters_orgtype($ORGTYPE_ID, $params) {
        $this->db->where('ORGTYPE_ID', $ORGTYPE_ID);
        $response = $this->db->update('masters_orgtype', $params);
        if ($response) {
            return "masters_orgtype updated successfully";
        } else {
            return "Error occuring while updating masters_orgtype";
        }
    }

    /*
     * function to delete masters_orgtype
     */

    function delete_masters_orgtype($ORGTYPE_ID) {
        $response = $this->db->delete('masters_orgtype', array('ORGTYPE_ID' => $ORGTYPE_ID));
        if ($response) {
            return "masters_orgtype deleted successfully";
        } else {
            return "Error occuring while deleting masters_orgtype";
        }
    }

}
