<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Masters_cust_comp_info_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /*
     * Get masters_cust_comp_info by COMPANY_ID
     */

    function get_masters_cust_comp_info($COMPANY_ID) {
        return $this->db->get_where('masters_cust_comp_info', array('COMPANY_ID' => $COMPANY_ID))->row_array();
    }

    /*
     * Get all masters_cust_comp_info
     */

    function get_all_masters_cust_comp_info() {
        return $this->db->get('masters_cust_comp_info')->result_array();
    }

    /**
     * Function to get all masters customer company info data
     * 
     * @param type $request
     * @param type $user_data
     * 
     * @return type
     */
    function getAllMastersCustCompInfoData($request, $user_data = array()) {
        try {
            $sql_details = array('user' => $this->db->username, 'pass' => $this->db->password, 'db' => $this->db->database, 'host' => $this->db->hostname);
            $request['searchcolumns'] = array();

            $columns = array(
                array(
                    'db' => 'COMPANY_ID',
                    'dt' => 'DT_RowId',
                    'formatter' => function( $d, $row ) {
                        return 'row_' . $d;
                    }
                ),
                array('db' => 'COMPANY_ID',
                    'dt' => 0,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'COMPANY_CODE',
                    'dt' => 1,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'COMPANY_NAME',
                    'dt' => 2,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'COMPANY_ADDRESS',
                    'dt' => 3,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'COMPANY_CITY',
                    'dt' => 4,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'STATE_ID',
                    'dt' => 5,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'COMPANY_POSTCODE',
                    'dt' => 6,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'COMPANY_PHONE1',
                    'dt' => 7,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'COMPANY_PHONE2',
                    'dt' => 8,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'COMPANY_FAX',
                    'dt' => 9,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'COMPANY_CREDIT_LIMIT',
                    'dt' => 10,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'COMPANY_SALARY_DAY_FROM1',
                    'dt' => 11,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'COMPANY_SALARY_DAY_TO1',
                    'dt' => 12,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'COMPANY_SALARY_DAY_FROM2',
                    'dt' => 13,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'COMPANY_SALARY_DAY_TO2',
                    'dt' => 14,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'PIC_NAME',
                    'dt' => 15,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'PIC_DESIGNATION',
                    'dt' => 16,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'PIC_CONTACT_NO',
                    'dt' => 17,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'PIC_MOBILE_NO',
                    'dt' => 18,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'COMPANY_BALANCE_CREDIT_LIMIT',
                    'dt' => 19,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'COMPANY_ID',
                    'dt' => 20,
                    'formatter' => function($d, $row) {
                        $returnString = "";
                        $returnString .= '<a href="' . site_url('masters_cust_comp_info/edit/' . $row['COMPANY_ID']) . '" class="btn btn-info btn-xs"><span class="fa fa-pencil"></span> Edit</a><br>';
                        $returnString .= '<a href="' . site_url('masters_cust_comp_info/remove/' . $row['COMPANY_ID']) . '" class="btn btn-danger btn-xs"><span class="fa fa-trash"></span> Delete</a>';
                        return $returnString;
                    }
                )
            );

            $join = "";
            $where = "";

            $query_columns_array = array("COMPANY_ID, COMPANY_CODE, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_CITY, STATE_ID, COMPANY_POSTCODE, COMPANY_PHONE1, COMPANY_PHONE2, COMPANY_FAX, COMPANY_CREDIT_LIMIT, COMPANY_SALARY_DAY_FROM1, COMPANY_SALARY_DAY_TO1, COMPANY_SALARY_DAY_FROM2, COMPANY_SALARY_DAY_TO2, PIC_NAME, PIC_DESIGNATION , PIC_CONTACT_NO, PIC_MOBILE_NO, COMPANY_BALANCE_CREDIT_LIMIT");

            $custom_where = array();
            $where .= " WHERE CREATED_BY = " . $_SESSION['user']['LOGIN_ID'] . " AND IS_ACTIVE = 1";
            $custom_where_string = (count($custom_where) > 0) ? implode(" AND ", array_unique($custom_where)) : "";
            $request['custom_where'] = $custom_where_string;
            $query_columns = implode(",", array_unique($query_columns_array));
            $sql_query = 'SELECT $query_columns from masters_cust_comp_info' . $join . $where;
            $result = datatable::simple($request, $sql_details, $sql_query, $query_columns, $columns);
            $start = $_REQUEST['start'];
            return $result;
        } catch (Exception $e) {
            log_message("Error : ", $this->db->_error_message());
            return fasle;
        }
    }

    /*
     * function to add new masters_cust_comp_info
     */

    function add_masters_cust_comp_info($params) {
        $this->db->insert('masters_cust_comp_info', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update masters_cust_comp_info
     */

    function update_masters_cust_comp_info($COMPANY_ID, $params) {
        $this->db->where('COMPANY_ID', $COMPANY_ID);
        $response = $this->db->update('masters_cust_comp_info', $params);
        if ($response) {
            return "masters_cust_comp_info updated successfully";
        } else {
            return "Error occuring while updating masters_cust_comp_info";
        }
    }

    /*
     * function to delete masters_cust_comp_info
     */

    function delete_masters_cust_comp_info($COMPANY_ID) {
        $response = $this->db->delete('masters_cust_comp_info', array('COMPANY_ID' => $COMPANY_ID));
        if ($response) {
            return "masters_cust_comp_info deleted successfully";
        } else {
            return "Error occuring while deleting masters_cust_comp_info";
        }
    }

}
