<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Masters_daily_gold_price_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /*
     * Get masters_daily_gold_price by GOLD_PRICE_ID
     */

    function get_masters_daily_gold_price($GOLD_PRICE_ID) {
        return $this->db->get_where('masters_daily_gold_price', array('GOLD_PRICE_ID' => $GOLD_PRICE_ID))->row_array();
    }

    /*
     * Get all masters_daily_gold_price
     */

    function get_all_masters_daily_gold_price() {
        return $this->db->get('masters_daily_gold_price')->result_array();
    }

    /**
     * FUnction to get all masters daily gold price data
     * 
     * @param type $request
     * @param type $user_data
     * 
     * @return type
     */
    function getAllMastersDailyGoldPriceData($request, $user_data = array()) {
        try {
            $sql_details = array('user' => $this->db->username, 'pass' => $this->db->password, 'db' => $this->db->database, 'host' => $this->db->hostname);
            $request['searchcolumns'] = array();

            $columns = array(
                array(
                    'db' => 'GOLD_PRICE_ID',
                    'dt' => 'DT_RowId',
                    'formatter' => function( $d, $row ) {
                        return 'row_' . $d;
                    }
                ),
                array('db' => 'GOLD_PRICE_ID',
                    'dt' => 0,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'CARAT_ID',
                    'dt' => 1,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'GOLD_PRICE_DATE',
                    'dt' => 2,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'GOLD_PRICE',
                    'dt' => 3,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'GOLD_PRICE_FACTOR',
                    'dt' => 4,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'GOLD_PRICE_BASIS',
                    'dt' => 5,
                    'formatter' => function($d, $row) {
                        return !empty($d) ? $d : "N/A";
                    }
                ),
                array('db' => 'GOLD_PRICE_ID',
                    'dt' => 6,
                    'formatter' => function($d, $row) {
                        $returnString = "";
                        $returnString .= '<a href="' . site_url('masters_daily_gold_price/edit/' . $row['GOLD_PRICE_ID']) . '" class="btn btn-info btn-xs"><span class="fa fa-pencil"></span> Edit</a><br>';
                        $returnString .= '<a href="' . site_url('masters_daily_gold_price/remove/' . $row['GOLD_PRICE_ID']) . '" class="btn btn-danger btn-xs"><span class="fa fa-trash"></span> Delete</a>';
                        return $returnString;
                    }
                )
            );

            $join = "";
            $where = "";

            $query_columns_array = array("GOLD_PRICE_ID, CARAT_ID, GOLD_PRICE_DATE, GOLD_PRICE, GOLD_PRICE_FACTOR, GOLD_PRICE_BASIS");

            $custom_where = array();
            $where .= " WHERE CREATED_BY = " . $_SESSION['user']['LOGIN_ID'] . " AND  IS_ACTIVE = 1";
            $custom_where_string = (count($custom_where) > 0) ? implode(" AND ", array_unique($custom_where)) : "";
            $request['custom_where'] = $custom_where_string;
            $query_columns = implode(",", array_unique($query_columns_array));
            $sql_query = 'SELECT $query_columns from masters_daily_gold_price' . $join . $where;
            $result = datatable::simple($request, $sql_details, $sql_query, $query_columns, $columns);
            $start = $_REQUEST['start'];
            return $result;
        } catch (Exception $e) {
            log_message("Error : ", $this->db->_error_message());
            return fasle;
        }
    }

    /*
     * function to add new masters_daily_gold_price
     */

    function add_masters_daily_gold_price($params) {
        $this->db->insert('masters_daily_gold_price', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update masters_daily_gold_price
     */

    function update_masters_daily_gold_price($GOLD_PRICE_ID, $params) {
        $this->db->where('GOLD_PRICE_ID', $GOLD_PRICE_ID);
        $response = $this->db->update('masters_daily_gold_price', $params);
        if ($response) {
            return "masters_daily_gold_price updated successfully";
        } else {
            return "Error occuring while updating masters_daily_gold_price";
        }
    }

    /*
     * function to delete masters_daily_gold_price
     */

    function delete_masters_daily_gold_price($GOLD_PRICE_ID) {
        $response = $this->db->delete('masters_daily_gold_price', array('GOLD_PRICE_ID' => $GOLD_PRICE_ID));
        if ($response) {
            return "masters_daily_gold_price deleted successfully";
        } else {
            return "Error occuring while deleting masters_daily_gold_price";
        }
    }

}
