<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Masters_cust_comp_info_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get masters_cust_comp_info by COMPANY_ID
     */
    function get_masters_cust_comp_info($COMPANY_ID)
    {
        return $this->db->get_where('masters_cust_comp_info',array('COMPANY_ID'=>$COMPANY_ID))->row_array();
    }
    
    /*
     * Get all masters_cust_comp_info
     */
    function get_all_masters_cust_comp_info()
    {
        return $this->db->get('masters_cust_comp_info')->result_array();
    }
    
    /*
     * function to add new masters_cust_comp_info
     */
    function add_masters_cust_comp_info($params)
    {
        $this->db->insert('masters_cust_comp_info',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update masters_cust_comp_info
     */
    function update_masters_cust_comp_info($COMPANY_ID,$params)
    {
        $this->db->where('COMPANY_ID',$COMPANY_ID);
        $response = $this->db->update('masters_cust_comp_info',$params);
        if($response)
        {
            return "masters_cust_comp_info updated successfully";
        }
        else
        {
            return "Error occuring while updating masters_cust_comp_info";
        }
    }
    
    /*
     * function to delete masters_cust_comp_info
     */
    function delete_masters_cust_comp_info($COMPANY_ID)
    {
        $response = $this->db->delete('masters_cust_comp_info',array('COMPANY_ID'=>$COMPANY_ID));
        if($response)
        {
            return "masters_cust_comp_info deleted successfully";
        }
        else
        {
            return "Error occuring while deleting masters_cust_comp_info";
        }
    }
}
