<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Masters_loan_pay_term_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get masters_loan_pay_term by LOANTERM_ID
     */
    function get_masters_loan_pay_term($LOANTERM_ID)
    {
        return $this->db->get_where('masters_loan_pay_terms',array('LOANTERM_ID'=>$LOANTERM_ID))->row_array();
    }
    
    /*
     * Get all masters_loan_pay_terms
     */
    function get_all_masters_loan_pay_terms()
    {
        return $this->db->get('masters_loan_pay_terms')->result_array();
    }
    
    /*
     * function to add new masters_loan_pay_term
     */
    function add_masters_loan_pay_term($params)
    {
        $this->db->insert('masters_loan_pay_terms',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update masters_loan_pay_term
     */
    function update_masters_loan_pay_term($LOANTERM_ID,$params)
    {
        $this->db->where('LOANTERM_ID',$LOANTERM_ID);
        $response = $this->db->update('masters_loan_pay_terms',$params);
        if($response)
        {
            return "masters_loan_pay_term updated successfully";
        }
        else
        {
            return "Error occuring while updating masters_loan_pay_term";
        }
    }
    
    /*
     * function to delete masters_loan_pay_term
     */
    function delete_masters_loan_pay_term($LOANTERM_ID)
    {
        $response = $this->db->delete('masters_loan_pay_terms',array('LOANTERM_ID'=>$LOANTERM_ID));
        if($response)
        {
            return "masters_loan_pay_term deleted successfully";
        }
        else
        {
            return "Error occuring while deleting masters_loan_pay_term";
        }
    }
}
