<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Masters_carat_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get masters_carat by CARAT_ID
     */
    function get_masters_carat($CARAT_ID)
    {
        return $this->db->get_where('masters_carat',array('CARAT_ID'=>$CARAT_ID))->row_array();
    }
    
    /*
     * Get all masters_carat
     */
    function get_all_masters_carat()
    {
        return $this->db->get('masters_carat')->result_array();
    }
    
    /*
     * function to add new masters_carat
     */
    function add_masters_carat($params)
    {
        $this->db->insert('masters_carat',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update masters_carat
     */
    function update_masters_carat($CARAT_ID,$params)
    {
        $this->db->where('CARAT_ID',$CARAT_ID);
        $response = $this->db->update('masters_carat',$params);
        if($response)
        {
            return "masters_carat updated successfully";
        }
        else
        {
            return "Error occuring while updating masters_carat";
        }
    }
    
    /*
     * function to delete masters_carat
     */
    function delete_masters_carat($CARAT_ID)
    {
        $response = $this->db->delete('masters_carat',array('CARAT_ID'=>$CARAT_ID));
        if($response)
        {
            return "masters_carat deleted successfully";
        }
        else
        {
            return "Error occuring while deleting masters_carat";
        }
    }
}
