<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Role_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get role by ROLE_ID
     */
    function get_role($ROLE_ID)
    {
        return $this->db->get_where('roles',array('ROLE_ID'=>$ROLE_ID))->row_array();
    }
    
    /*
     * Get all roles
     */
    function get_all_roles()
    {
        return $this->db->get('roles')->result_array();
    }
    
    /*
     * function to add new role
     */
    function add_role($params)
    {
        $this->db->insert('roles',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update role
     */
    function update_role($ROLE_ID,$params)
    {
        $this->db->where('ROLE_ID',$ROLE_ID);
        $response = $this->db->update('roles',$params);
        if($response)
        {
            return "role updated successfully";
        }
        else
        {
            return "Error occuring while updating role";
        }
    }
    
    /*
     * function to delete role
     */
    function delete_role($ROLE_ID)
    {
        $response = $this->db->delete('roles',array('ROLE_ID'=>$ROLE_ID));
        if($response)
        {
            return "role deleted successfully";
        }
        else
        {
            return "Error occuring while deleting role";
        }
    }
}
