<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Userrights_by_role_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get userrights_by_role by UR_ID
     */
    function get_userrights_by_role($UR_ID)
    {
        return $this->db->get_where('userrights_by_roles',array('UR_ID'=>$UR_ID))->row_array();
    }
    
    /*
     * Get all userrights_by_roles
     */
    function get_all_userrights_by_roles()
    {
        return $this->db->get('userrights_by_roles')->result_array();
    }
    
    /*
     * function to add new userrights_by_role
     */
    function add_userrights_by_role($params)
    {
        $this->db->insert('userrights_by_roles',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update userrights_by_role
     */
    function update_userrights_by_role($UR_ID,$params)
    {
        $this->db->where('UR_ID',$UR_ID);
        $response = $this->db->update('userrights_by_roles',$params);
        if($response)
        {
            return "userrights_by_role updated successfully";
        }
        else
        {
            return "Error occuring while updating userrights_by_role";
        }
    }
    
    /*
     * function to delete userrights_by_role
     */
    function delete_userrights_by_role($UR_ID)
    {
        $response = $this->db->delete('userrights_by_roles',array('UR_ID'=>$UR_ID));
        if($response)
        {
            return "userrights_by_role deleted successfully";
        }
        else
        {
            return "Error occuring while deleting userrights_by_role";
        }
    }
}
